export const GLADIATOR_PERMANENT_TRAITS = {
  disciplined: {
    nameKey: 'traits.disciplined.name',
    descriptionKey: 'traits.disciplined.description',
    visual: { iconName: 'training', color: '#5f8fb7' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 8,
    marketWeight: 100,
    modifiers: [{ type: 'trainingExperienceMultiplier', value: 1.06 }],
  },
  lazy: {
    nameKey: 'traits.lazy.name',
    descriptionKey: 'traits.lazy.description',
    visual: { iconName: 'energy', color: '#9a8d74' },
    showAlert: false,
    marketPolarity: 'negative',
    marketPriceModifierPercent: -8,
    marketWeight: 100,
    modifiers: [{ type: 'trainingExperienceMultiplier', value: 0.92 }],
  },
  brave: {
    nameKey: 'traits.brave.name',
    descriptionKey: 'traits.brave.description',
    visual: { iconName: 'victory', color: '#d6a34a' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 6,
    marketWeight: 100,
    modifiers: [{ type: 'combatMoraleBonus', value: 6 }],
  },
  cowardly: {
    nameKey: 'traits.cowardly.name',
    descriptionKey: 'traits.cowardly.description',
    visual: { iconName: 'defeat', color: '#b55339' },
    showAlert: false,
    marketPolarity: 'negative',
    marketPriceModifierPercent: -10,
    marketWeight: 100,
    modifiers: [{ type: 'combatMoraleBonus', value: -7 }],
  },
  ambitious: {
    nameKey: 'traits.ambitious.name',
    descriptionKey: 'traits.ambitious.description',
    visual: { iconName: 'level', color: '#78c46b' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 7,
    marketWeight: 100,
    modifiers: [{ type: 'combatExperienceMultiplier', value: 1.08 }],
  },
  fragile: {
    nameKey: 'traits.fragile.name',
    descriptionKey: 'traits.fragile.description',
    visual: { iconName: 'injuryRisk', color: '#b33a2e' },
    showAlert: false,
    marketPolarity: 'negative',
    marketPriceModifierPercent: -12,
    marketWeight: 100,
    modifiers: [{ type: 'injuryRiskMultiplier', value: 1.25 }],
  },
  crowdFavorite: {
    nameKey: 'traits.crowdFavorite.name',
    descriptionKey: 'traits.crowdFavorite.description',
    visual: { iconName: 'reputation', color: '#d39942' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 12,
    marketWeight: 100,
    modifiers: [{ type: 'arenaRewardMultiplier', value: 1.1 }],
  },
  rivalrous: {
    nameKey: 'traits.rivalrous.name',
    descriptionKey: 'traits.rivalrous.description',
    visual: { iconName: 'combatPressure', color: '#b55339' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: 2,
    marketWeight: 100,
    modifiers: [
      { type: 'combatEnergyBonus', value: 5 },
      { type: 'combatMoraleBonus', value: -4 },
    ],
  },
  stoic: {
    nameKey: 'traits.stoic.name',
    descriptionKey: 'traits.stoic.description',
    visual: { iconName: 'defense', color: '#78c46b' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 8,
    marketWeight: 100,
    modifiers: [{ type: 'injuryRiskMultiplier', value: 0.88 }],
  },
  quickLearner: {
    nameKey: 'traits.quickLearner.name',
    descriptionKey: 'traits.quickLearner.description',
    visual: { iconName: 'xp', color: '#78c46b' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 14,
    marketWeight: 100,
    exclusiveGroup: 'learningPace',
    modifiers: [{ type: 'trainingExperienceMultiplier', value: 1.12 }],
  },
  slowLearner: {
    nameKey: 'traits.slowLearner.name',
    descriptionKey: 'traits.slowLearner.description',
    visual: { iconName: 'xp', color: '#9a8d74' },
    showAlert: false,
    marketPolarity: 'negative',
    marketPriceModifierPercent: -12,
    marketWeight: 100,
    exclusiveGroup: 'learningPace',
    modifiers: [{ type: 'trainingExperienceMultiplier', value: 0.88 }],
  },
  ironJaw: {
    nameKey: 'traits.ironJaw.name',
    descriptionKey: 'traits.ironJaw.description',
    visual: { iconName: 'health', color: '#b56f3c' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 12,
    marketWeight: 100,
    modifiers: [{ type: 'skillBonus', skill: 'life', value: 1 }],
  },
  broadShouldered: {
    nameKey: 'traits.broadShouldered.name',
    descriptionKey: 'traits.broadShouldered.description',
    visual: { iconName: 'strength', color: '#b56f3c' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: 10,
    marketWeight: 100,
    exclusiveGroup: 'bodyFrame',
    modifiers: [
      { type: 'skillBonus', skill: 'strength', value: 1 },
      { type: 'combatEnergyBonus', value: -2 },
    ],
  },
  fleetFooted: {
    nameKey: 'traits.fleetFooted.name',
    descriptionKey: 'traits.fleetFooted.description',
    visual: { iconName: 'agility', color: '#5f8fb7' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 12,
    marketWeight: 100,
    exclusiveGroup: 'mobility',
    modifiers: [{ type: 'skillBonus', skill: 'agility', value: 1 }],
  },
  shieldWise: {
    nameKey: 'traits.shieldWise.name',
    descriptionKey: 'traits.shieldWise.description',
    visual: { iconName: 'defense', color: '#5f8fb7' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 10,
    marketWeight: 100,
    modifiers: [{ type: 'skillBonus', skill: 'defense', value: 1 }],
  },
  limping: {
    nameKey: 'traits.limping.name',
    descriptionKey: 'traits.limping.description',
    visual: { iconName: 'injuryRisk', color: '#b33a2e' },
    showAlert: false,
    marketPolarity: 'negative',
    marketPriceModifierPercent: -15,
    marketWeight: 100,
    exclusiveGroup: 'mobility',
    modifiers: [
      { type: 'skillBonus', skill: 'agility', value: -1 },
      { type: 'injuryRiskMultiplier', value: 1.12 },
    ],
  },
  glassKnee: {
    nameKey: 'traits.glassKnee.name',
    descriptionKey: 'traits.glassKnee.description',
    visual: { iconName: 'injuryRisk', color: '#b33a2e' },
    showAlert: false,
    marketPolarity: 'negative',
    marketPriceModifierPercent: -20,
    marketWeight: 100,
    exclusiveGroup: 'mobility',
    modifiers: [
      { type: 'skillBonus', skill: 'agility', value: -1 },
      { type: 'injuryRiskMultiplier', value: 1.3 },
    ],
  },
  oneEyed: {
    nameKey: 'traits.oneEyed.name',
    descriptionKey: 'traits.oneEyed.description',
    visual: { iconName: 'view', color: '#8f8a80' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: -6,
    marketWeight: 100,
    exclusiveGroup: 'sight',
    modifiers: [
      { type: 'skillBonus', skill: 'defense', value: -1 },
      { type: 'combatMoraleBonus', value: 3 },
    ],
  },
  scarredLegend: {
    nameKey: 'traits.scarredLegend.name',
    descriptionKey: 'traits.scarredLegend.description',
    visual: { iconName: 'reputation', color: '#d39942' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 12,
    marketWeight: 100,
    modifiers: [
      { type: 'arenaRewardMultiplier', value: 1.08 },
      { type: 'combatMoraleBonus', value: 3 },
    ],
  },
  painTolerant: {
    nameKey: 'traits.painTolerant.name',
    descriptionKey: 'traits.painTolerant.description',
    visual: { iconName: 'health', color: '#78c46b' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 15,
    marketWeight: 100,
    modifiers: [
      { type: 'injuryRiskMultiplier', value: 0.85 },
      { type: 'skillBonus', skill: 'life', value: 1 },
    ],
  },
  showboater: {
    nameKey: 'traits.showboater.name',
    descriptionKey: 'traits.showboater.description',
    visual: { iconName: 'reputation', color: '#d39942' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: 7,
    marketWeight: 100,
    modifiers: [
      { type: 'arenaRewardMultiplier', value: 1.14 },
      { type: 'combatEnergyBonus', value: -3 },
    ],
  },
  humble: {
    nameKey: 'traits.humble.name',
    descriptionKey: 'traits.humble.description',
    visual: { iconName: 'morale', color: '#ffd76a' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: -1,
    marketWeight: 100,
    modifiers: [
      { type: 'combatMoraleBonus', value: 2 },
      { type: 'arenaRewardMultiplier', value: 0.94 },
    ],
  },
  brawler: {
    nameKey: 'traits.brawler.name',
    descriptionKey: 'traits.brawler.description',
    visual: { iconName: 'combatStrike', color: '#b56f3c' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: 3,
    marketWeight: 100,
    exclusiveGroup: 'combatStyle',
    modifiers: [
      { type: 'skillBonus', skill: 'strength', value: 1 },
      { type: 'skillBonus', skill: 'defense', value: -1 },
    ],
  },
  tactical: {
    nameKey: 'traits.tactical.name',
    descriptionKey: 'traits.tactical.description',
    visual: { iconName: 'assignment', color: '#5f8fb7' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 13,
    marketWeight: 100,
    exclusiveGroup: 'combatStyle',
    modifiers: [
      { type: 'skillBonus', skill: 'defense', value: 1 },
      { type: 'combatExperienceMultiplier', value: 1.05 },
    ],
  },
  reckless: {
    nameKey: 'traits.reckless.name',
    descriptionKey: 'traits.reckless.description',
    visual: { iconName: 'warning', color: '#b55339' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: -2,
    marketWeight: 100,
    exclusiveGroup: 'combatStyle',
    modifiers: [
      { type: 'skillBonus', skill: 'strength', value: 1 },
      { type: 'skillBonus', skill: 'defense', value: -1 },
      { type: 'injuryRiskMultiplier', value: 1.25 },
    ],
  },
  patient: {
    nameKey: 'traits.patient.name',
    descriptionKey: 'traits.patient.description',
    visual: { iconName: 'defense', color: '#8f8a80' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: 5,
    marketWeight: 100,
    modifiers: [
      { type: 'skillBonus', skill: 'defense', value: 1 },
      { type: 'combatEnergyBonus', value: -2 },
    ],
  },
  hotBlooded: {
    nameKey: 'traits.hotBlooded.name',
    descriptionKey: 'traits.hotBlooded.description',
    visual: { iconName: 'morale', color: '#b55339' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: 2,
    marketWeight: 100,
    modifiers: [
      { type: 'combatMoraleBonus', value: 5 },
      { type: 'injuryRiskMultiplier', value: 1.15 },
    ],
  },
  veteranInstinct: {
    nameKey: 'traits.veteranInstinct.name',
    descriptionKey: 'traits.veteranInstinct.description',
    visual: { iconName: 'record', color: '#d6a34a' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 13,
    marketWeight: 100,
    modifiers: [
      { type: 'combatMoraleBonus', value: 4 },
      { type: 'combatExperienceMultiplier', value: 1.06 },
    ],
  },
  streetRaised: {
    nameKey: 'traits.streetRaised.name',
    descriptionKey: 'traits.streetRaised.description',
    visual: { iconName: 'agility', color: '#5f8fb7' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: 5,
    marketWeight: 100,
    modifiers: [
      { type: 'skillBonus', skill: 'agility', value: 1 },
      { type: 'combatMoraleBonus', value: -2 },
    ],
  },
  nobleBearing: {
    nameKey: 'traits.nobleBearing.name',
    descriptionKey: 'traits.nobleBearing.description',
    visual: { iconName: 'landmark', color: '#d6a34a' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 14,
    marketWeight: 100,
    modifiers: [
      { type: 'arenaRewardMultiplier', value: 1.12 },
      { type: 'combatMoraleBonus', value: 2 },
    ],
  },
  debtBurdened: {
    nameKey: 'traits.debtBurdened.name',
    descriptionKey: 'traits.debtBurdened.description',
    visual: { iconName: 'treasury', color: '#b55339' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: -3,
    marketWeight: 100,
    modifiers: [
      { type: 'combatExperienceMultiplier', value: 1.08 },
      { type: 'combatMoraleBonus', value: -5 },
    ],
  },
  loyal: {
    nameKey: 'traits.loyal.name',
    descriptionKey: 'traits.loyal.description',
    visual: { iconName: 'check', color: '#78c46b' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 7,
    marketWeight: 100,
    modifiers: [
      { type: 'combatMoraleBonus', value: 3 },
      { type: 'trainingExperienceMultiplier', value: 1.03 },
    ],
  },
  insubordinate: {
    nameKey: 'traits.insubordinate.name',
    descriptionKey: 'traits.insubordinate.description',
    visual: { iconName: 'warning', color: '#b55339' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: -3,
    marketWeight: 100,
    modifiers: [
      { type: 'trainingExperienceMultiplier', value: 0.94 },
      { type: 'combatMoraleBonus', value: 3 },
    ],
  },
  careful: {
    nameKey: 'traits.careful.name',
    descriptionKey: 'traits.careful.description',
    visual: { iconName: 'injuryRisk', color: '#78c46b' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: 3,
    marketWeight: 100,
    modifiers: [
      { type: 'injuryRiskMultiplier', value: 0.82 },
      { type: 'combatEnergyBonus', value: -3 },
    ],
  },
  sickly: {
    nameKey: 'traits.sickly.name',
    descriptionKey: 'traits.sickly.description',
    visual: { iconName: 'health', color: '#b33a2e' },
    showAlert: false,
    marketPolarity: 'negative',
    marketPriceModifierPercent: -16,
    marketWeight: 100,
    modifiers: [
      { type: 'skillBonus', skill: 'life', value: -1 },
      { type: 'injuryRiskMultiplier', value: 1.2 },
    ],
  },
  giantFrame: {
    nameKey: 'traits.giantFrame.name',
    descriptionKey: 'traits.giantFrame.description',
    visual: { iconName: 'strength', color: '#b56f3c' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: 15,
    marketWeight: 100,
    exclusiveGroup: 'bodyFrame',
    modifiers: [
      { type: 'skillBonus', skill: 'strength', value: 1 },
      { type: 'skillBonus', skill: 'life', value: 1 },
      { type: 'skillBonus', skill: 'agility', value: -1 },
    ],
  },
  smallTarget: {
    nameKey: 'traits.smallTarget.name',
    descriptionKey: 'traits.smallTarget.description',
    visual: { iconName: 'agility', color: '#5f8fb7' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: 10,
    marketWeight: 100,
    exclusiveGroup: 'bodyFrame',
    modifiers: [
      { type: 'skillBonus', skill: 'agility', value: 1 },
      { type: 'skillBonus', skill: 'defense', value: 1 },
      { type: 'skillBonus', skill: 'strength', value: -1 },
    ],
  },
  oldScar: {
    nameKey: 'traits.oldScar.name',
    descriptionKey: 'traits.oldScar.description',
    visual: { iconName: 'health', color: '#b56f3c' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: -2,
    marketWeight: 100,
    modifiers: [
      { type: 'injuryRiskMultiplier', value: 1.08 },
      { type: 'combatMoraleBonus', value: 3 },
    ],
  },
  entertainer: {
    nameKey: 'traits.entertainer.name',
    descriptionKey: 'traits.entertainer.description',
    visual: { iconName: 'reputation', color: '#d39942' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: 8,
    marketWeight: 100,
    modifiers: [
      { type: 'arenaRewardMultiplier', value: 1.16 },
      { type: 'combatExperienceMultiplier', value: 0.95 },
    ],
  },
  oathKeeper: {
    nameKey: 'traits.oathKeeper.name',
    descriptionKey: 'traits.oathKeeper.description',
    visual: { iconName: 'check', color: '#78c46b' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 9,
    marketWeight: 100,
    modifiers: [
      { type: 'trainingExperienceMultiplier', value: 1.04 },
      { type: 'combatMoraleBonus', value: 4 },
    ],
  },
  gambler: {
    nameKey: 'traits.gambler.name',
    descriptionKey: 'traits.gambler.description',
    visual: { iconName: 'dice', color: '#d6a34a' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: 4,
    marketWeight: 100,
    modifiers: [
      { type: 'arenaRewardMultiplier', value: 1.12 },
      { type: 'combatMoraleBonus', value: -3 },
    ],
  },
  sandReader: {
    nameKey: 'traits.sandReader.name',
    descriptionKey: 'traits.sandReader.description',
    visual: { iconName: 'agility', color: '#5f8fb7' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 13,
    marketWeight: 100,
    modifiers: [
      { type: 'skillBonus', skill: 'agility', value: 1 },
      { type: 'combatExperienceMultiplier', value: 1.04 },
    ],
  },
  hardDrinker: {
    nameKey: 'traits.hardDrinker.name',
    descriptionKey: 'traits.hardDrinker.description',
    visual: { iconName: 'energy', color: '#9a8d74' },
    showAlert: false,
    marketPolarity: 'negative',
    marketPriceModifierPercent: -10,
    marketWeight: 100,
    modifiers: [
      { type: 'trainingExperienceMultiplier', value: 0.93 },
      { type: 'injuryRiskMultiplier', value: 1.12 },
    ],
  },
  herbalist: {
    nameKey: 'traits.herbalist.name',
    descriptionKey: 'traits.herbalist.description',
    visual: { iconName: 'health', color: '#78c46b' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 8,
    marketWeight: 100,
    modifiers: [
      { type: 'injuryRiskMultiplier', value: 0.9 },
      { type: 'trainingExperienceMultiplier', value: 1.02 },
    ],
  },
  nightBlind: {
    nameKey: 'traits.nightBlind.name',
    descriptionKey: 'traits.nightBlind.description',
    visual: { iconName: 'view', color: '#9a8d74' },
    showAlert: false,
    marketPolarity: 'negative',
    marketPriceModifierPercent: -12,
    marketWeight: 100,
    exclusiveGroup: 'sight',
    modifiers: [
      { type: 'skillBonus', skill: 'agility', value: -1 },
      { type: 'combatMoraleBonus', value: -2 },
    ],
  },
  crowdShy: {
    nameKey: 'traits.crowdShy.name',
    descriptionKey: 'traits.crowdShy.description',
    visual: { iconName: 'morale', color: '#9a8d74' },
    showAlert: false,
    marketPolarity: 'negative',
    marketPriceModifierPercent: -13,
    marketWeight: 100,
    modifiers: [
      { type: 'arenaRewardMultiplier', value: 0.9 },
      { type: 'combatMoraleBonus', value: -3 },
    ],
  },
  revengeDriven: {
    nameKey: 'traits.revengeDriven.name',
    descriptionKey: 'traits.revengeDriven.description',
    visual: { iconName: 'combatPressure', color: '#b55339' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: 8,
    marketWeight: 100,
    modifiers: [
      { type: 'combatEnergyBonus', value: 6 },
      { type: 'combatExperienceMultiplier', value: 1.04 },
      { type: 'injuryRiskMultiplier', value: 1.1 },
    ],
  },
  fragileEgo: {
    nameKey: 'traits.fragileEgo.name',
    descriptionKey: 'traits.fragileEgo.description',
    visual: { iconName: 'morale', color: '#b55339' },
    showAlert: false,
    marketPolarity: 'negative',
    marketPriceModifierPercent: -6,
    marketWeight: 100,
    modifiers: [
      { type: 'combatMoraleBonus', value: -5 },
      { type: 'combatExperienceMultiplier', value: 1.05 },
    ],
  },
  steadyHands: {
    nameKey: 'traits.steadyHands.name',
    descriptionKey: 'traits.steadyHands.description',
    visual: { iconName: 'defense', color: '#5f8fb7' },
    showAlert: false,
    marketPolarity: 'positive',
    marketPriceModifierPercent: 10,
    marketWeight: 100,
    modifiers: [
      { type: 'skillBonus', skill: 'defense', value: 1 },
      { type: 'trainingExperienceMultiplier', value: 1.03 },
    ],
  },
  grimHumor: {
    nameKey: 'traits.grimHumor.name',
    descriptionKey: 'traits.grimHumor.description',
    visual: { iconName: 'morale', color: '#8f8a80' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: 2,
    marketWeight: 100,
    modifiers: [
      { type: 'combatMoraleBonus', value: 4 },
      { type: 'arenaRewardMultiplier', value: 0.96 },
    ],
  },
} as const;

export const GLADIATOR_TEMPORARY_TRAITS = {
  injury: {
    nameKey: 'traits.injury.name',
    descriptionKey: 'traits.injury.description',
    visual: { iconName: 'health', color: '#b33a2e' },
    showAlert: true,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: 0,
    marketWeight: 0,
    modifiers: [{ type: 'activityEligibility', value: false }],
    // Days applied when macro training creates an injury trait.
    trainingDurationDays: 2,
    // Days applied by event consequences that explicitly create an injury trait.
    eventDurationDays: 2,
    combat: {
      // Chance that a winning arena gladiator receives an injury trait.
      winChance: 0.05,
      // Chance that a losing arena gladiator receives an injury trait.
      lossChance: 0.3,
      // Minimum arena injury duration in days.
      minDurationDays: 2,
      // Maximum arena injury duration in days.
      maxDurationDays: 8,
    },
  },
  rest: {
    nameKey: 'traits.rest.name',
    descriptionKey: 'traits.rest.description',
    visual: { iconName: 'energy', color: '#7f7a6b' },
    showAlert: true,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: 0,
    marketWeight: 0,
    modifiers: [{ type: 'activityEligibility', value: false }],
    // Days applied by event choices that grant a gladiator rest.
    durationDays: 2,
  },
  victoryAura: {
    nameKey: 'traits.victoryAura.name',
    descriptionKey: 'traits.victoryAura.description',
    visual: { iconName: 'victory', color: '#d6a34a' },
    showAlert: false,
    marketPolarity: 'mixed',
    marketPriceModifierPercent: 0,
    marketWeight: 0,
    modifiers: [{ type: 'trainingExperienceMultiplier', value: 1.1 }],
    // Days applied after a Sunday arena victory.
    durationDays: 3,
  },
} as const;
