import type { DemoSaveDefinition } from './types';
import {
  createDemoSave,
  createMarketGladiator,
  createPurchasedBuilding,
} from './demo-save-builders';

const year = 5;
const week = 7;
const createdAtDay = 'saturday';

const save = createDemoSave({
  id: 'demo-advanced-ludus',
  ludusName: 'Ludus Invictus',
  ludus: {
    treasury: 12000,
    reputation: 450,
  },
  time: {
    year,
    week,
    dayOfWeek: createdAtDay,
  },
  buildings: {
    domus: createPurchasedBuilding({
      id: 'domus',
      level: 6,
    }),
    canteen: createPurchasedBuilding({
      id: 'canteen',
      level: 6,
    }),
    dormitory: createPurchasedBuilding({
      id: 'dormitory',
      level: 6,
      purchasedImprovementIds: ['strawBeds', 'woodenBeds', 'quietQuarters'],
    }),
    trainingGround: createPurchasedBuilding({
      id: 'trainingGround',
      level: 6,
      configuration: {
        defaultDoctrineId: 'brutalDiscipline',
      },
      purchasedImprovementIds: ['sparringRing', 'advancedDoctoreTools'],
      selectedPolicyId: 'brutalDiscipline',
    }),
  },
  gladiators: [
    {
      id: 'glad-demo-adv-maximus',
      name: 'Maximus Drusus',
      age: 34,
      experience: 4650,
      strength: 8,
      agility: 6,
      defense: 6,
      life: 5,
      reputation: 610,
      wins: 34,
      losses: 6,
      traits: ['crowdFavorite', 'stoic'],
    },
    {
      id: 'glad-demo-adv-severus',
      name: 'Severus Thrax',
      age: 29,
      experience: 3640,
      strength: 8,
      agility: 5,
      defense: 5,
      life: 4,
      reputation: 420,
      wins: 25,
      losses: 8,
      traits: ['brave'],
    },
    {
      id: 'glad-demo-adv-cassian',
      name: 'Cassian Lupus',
      age: 23,
      experience: 3180,
      strength: 5,
      agility: 8,
      defense: 4,
      life: 5,
      reputation: 310,
      wins: 18,
      losses: 5,
      traits: ['ambitious'],
    },
    {
      id: 'glad-demo-adv-brutus',
      name: 'Brutus Varro',
      age: 41,
      experience: 2750,
      strength: 6,
      agility: 4,
      defense: 7,
      life: 3,
      reputation: 280,
      wins: 20,
      losses: 11,
      traits: ['disciplined'],
    },
    {
      id: 'glad-demo-adv-nasica',
      name: 'Nasica Rufus',
      age: 27,
      experience: 2350,
      strength: 5,
      agility: 5,
      defense: 6,
      life: 4,
      reputation: 190,
      wins: 13,
      losses: 6,
      traits: ['stoic'],
    },
    {
      id: 'glad-demo-adv-syrianus',
      name: 'Syrianus Afer',
      age: 22,
      experience: 1980,
      strength: 5,
      agility: 6,
      defense: 4,
      life: 3,
      reputation: 150,
      wins: 9,
      losses: 7,
      traits: ['rivalrous'],
    },
  ],
  market: [
    createMarketGladiator({
      id: 'market-demo-advanced-1',
      name: 'Vettius Corax',
      age: 28,
      experience: 1050,
      strength: 5,
      agility: 4,
      defense: 5,
      life: 2,
      reputation: 160,
      wins: 12,
      losses: 4,
      traits: ['disciplined'],
      price: 550,
    }),
    createMarketGladiator({
      id: 'market-demo-advanced-2',
      name: 'Lucanus Ferox',
      age: 31,
      experience: 1330,
      strength: 6,
      agility: 3,
      defense: 5,
      life: 3,
      reputation: 210,
      wins: 16,
      losses: 7,
      traits: ['brave'],
      price: 625,
    }),
    createMarketGladiator({
      id: 'market-demo-advanced-3',
      name: 'Marcellus Vindex',
      age: 24,
      experience: 1640,
      strength: 4,
      agility: 7,
      defense: 4,
      life: 3,
      reputation: 180,
      wins: 14,
      losses: 3,
      traits: ['ambitious'],
      price: 700,
    }),
    createMarketGladiator({
      id: 'market-demo-advanced-4',
      name: 'Numerius Scaeva',
      age: 35,
      experience: 1980,
      strength: 5,
      agility: 3,
      defense: 7,
      life: 3,
      reputation: 240,
      wins: 19,
      losses: 9,
      traits: ['stoic'],
      price: 775,
    }),
    createMarketGladiator({
      id: 'market-demo-advanced-5',
      name: 'Appius Lupicinus',
      age: 26,
      experience: 2350,
      strength: 5,
      agility: 6,
      defense: 5,
      life: 4,
      reputation: 195,
      wins: 15,
      losses: 5,
      traits: ['crowdFavorite'],
      price: 875,
    }),
  ],
});

export const demoAdvancedLudus: DemoSaveDefinition = {
  id: 'demo-advanced-ludus',
  nameKey: 'demoSaves.advanced.name',
  descriptionKey: 'demoSaves.advanced.description',
  stageKey: 'demoSaves.stage.advanced',
  tags: ['demoSaves.tags.denseRoster', 'demoSaves.tags.weeklyPlanning'],
  save,
  preferredRoute: 'ludus',
  preferredCameraTarget: 'arena',
};
