import type { DemoSaveDefinition } from './types';
import {
  createDemoSave,
  createMarketGladiator,
  createPurchasedBuilding,
} from './demo-save-builders';

const year = 2;
const week = 4;
const createdAtDay = 'thursday';

const save = createDemoSave({
  id: 'demo-mid-ludus',
  ludusName: 'Ludus Ferrata',
  ludus: {
    treasury: 3200,
    reputation: 85,
  },
  time: {
    year,
    week,
    dayOfWeek: createdAtDay,
  },
  buildings: {
    domus: createPurchasedBuilding({
      id: 'domus',
      level: 4,
    }),
    canteen: createPurchasedBuilding({
      id: 'canteen',
      level: 3,
    }),
    dormitory: createPurchasedBuilding({
      id: 'dormitory',
      level: 4,
      purchasedImprovementIds: ['strawBeds', 'woodenBeds', 'quietQuarters'],
    }),
    trainingGround: createPurchasedBuilding({
      id: 'trainingGround',
      level: 4,
      configuration: {
        defaultDoctrineId: 'strengthDoctrine',
      },
      purchasedImprovementIds: ['sparringRing', 'advancedDoctoreTools'],
      selectedPolicyId: 'strengthDoctrine',
    }),
  },
  gladiators: [
    {
      id: 'glad-demo-mid-gaius',
      name: 'Gaius Flamma',
      age: 26,
      experience: 390,
      strength: 4,
      agility: 3,
      defense: 3,
      life: 3,
      reputation: 70,
      wins: 6,
      losses: 2,
      traits: ['brave', 'crowdFavorite'],
    },
    {
      id: 'glad-demo-mid-aulus',
      name: 'Aulus Niger',
      age: 24,
      experience: 230,
      strength: 3,
      agility: 4,
      defense: 2,
      life: 2,
      reputation: 45,
      wins: 4,
      losses: 3,
      traits: ['ambitious'],
    },
    {
      id: 'glad-demo-mid-quintus',
      name: 'Quintus Felix',
      age: 30,
      experience: 580,
      strength: 3,
      agility: 3,
      defense: 4,
      life: 4,
      reputation: 120,
      wins: 10,
      losses: 4,
      traits: ['disciplined', 'stoic'],
    },
    {
      id: 'glad-demo-mid-publius',
      name: 'Publius Corvus',
      age: 21,
      experience: 100,
      strength: 3,
      agility: 2,
      defense: 3,
      life: 2,
      reputation: 25,
      wins: 2,
      losses: 2,
      traits: ['fragile'],
    },
  ],
  market: [
    createMarketGladiator({
      id: 'market-demo-mid-1',
      name: 'Servius Ruga',
      age: 24,
      experience: 0,
      strength: 3,
      agility: 2,
      defense: 3,
      life: 2,
      reputation: 12,
      wins: 1,
      losses: 1,
      traits: ['stoic'],
      price: 300,
    }),
    createMarketGladiator({
      id: 'market-demo-mid-2',
      name: 'Lentulus Varo',
      age: 28,
      experience: 100,
      strength: 4,
      agility: 2,
      defense: 3,
      life: 2,
      reputation: 25,
      wins: 3,
      losses: 2,
      traits: ['brave'],
      price: 325,
    }),
    createMarketGladiator({
      id: 'market-demo-mid-3',
      name: 'Hostus Naso',
      age: 22,
      experience: 230,
      strength: 3,
      agility: 4,
      defense: 3,
      life: 2,
      reputation: 18,
      wins: 2,
      losses: 0,
      traits: ['ambitious'],
      price: 350,
    }),
    createMarketGladiator({
      id: 'market-demo-mid-4',
      name: 'Fabius Sura',
      age: 31,
      experience: 390,
      strength: 3,
      agility: 2,
      defense: 5,
      life: 3,
      reputation: 40,
      wins: 5,
      losses: 5,
      traits: ['disciplined'],
      price: 375,
    }),
    createMarketGladiator({
      id: 'market-demo-mid-5',
      name: 'Tarquinius Balbus',
      age: 20,
      experience: 580,
      strength: 3,
      agility: 4,
      defense: 3,
      life: 4,
      reputation: 8,
      wins: 1,
      losses: 0,
      traits: ['crowdFavorite'],
      price: 425,
    }),
  ],
});

export const demoMidLudus: DemoSaveDefinition = {
  id: 'demo-mid-ludus',
  nameKey: 'demoSaves.mid.name',
  descriptionKey: 'demoSaves.mid.description',
  stageKey: 'demoSaves.stage.mid',
  tags: ['demoSaves.tags.market', 'demoSaves.tags.alerts'],
  save,
  preferredRoute: 'ludus',
  preferredCameraTarget: 'market',
};
