import type { DemoSaveDefinition } from './types';
import {
  createDemoSave,
  createMarketGladiator,
  createPurchasedBuilding,
} from './demo-save-builders';

const save = createDemoSave({
  id: 'demo-early-ludus',
  ludusName: 'Ludus Primus',
  ludus: {
    treasury: 850,
    reputation: 5,
  },
  time: {
    year: 1,
    week: 1,
    dayOfWeek: 'monday',
  },
  buildings: {
    domus: createPurchasedBuilding({
      id: 'domus',
      level: 3,
    }),
    canteen: createPurchasedBuilding({
      id: 'canteen',
      level: 1,
    }),
    dormitory: createPurchasedBuilding({
      id: 'dormitory',
      level: 1,
    }),
    trainingGround: createPurchasedBuilding({
      id: 'trainingGround',
      level: 1,
      configuration: {
        defaultDoctrineId: 'balancedTraining',
      },
      selectedPolicyId: 'balancedTraining',
    }),
    pleasureHall: createPurchasedBuilding({
      id: 'pleasureHall',
      level: 1,
      configuration: {
        entertainmentPlanId: 'quietEvenings',
      },
      selectedPolicyId: 'quietEvenings',
    }),
    infirmary: createPurchasedBuilding({
      id: 'infirmary',
      level: 1,
      configuration: {
        carePolicyId: 'basicCare',
      },
      selectedPolicyId: 'basicCare',
    }),
  },
  gladiators: [
    {
      id: 'glad-demo-early-marcus',
      name: 'Marcus Varro',
      age: 19,
      strength: 7,
      agility: 8,
      defense: 5,
      life: 94,
      reputation: 0,
      wins: 0,
      losses: 0,
      traits: ['ambitious'],
    },
    {
      id: 'glad-demo-early-titus',
      name: 'Titus Marcellus',
      age: 18,
      strength: 5,
      agility: 6,
      defense: 9,
      life: 75,
      reputation: 10,
      wins: 1,
      losses: 0,
      traits: ['disciplined'],
    },
    {
      id: 'glad-demo-early-darius',
      name: 'Darius Nerva',
      age: 20,
      strength: 10,
      agility: 5,
      defense: 5,
      life: 45,
      reputation: 0,
      wins: 0,
      losses: 1,
      traits: ['fragile'],
    },
  ],
  market: [
    createMarketGladiator({
      id: 'market-demo-early-1',
      name: 'Nero Silvanus',
      age: 18,
      strength: 6,
      agility: 7,
      defense: 5,
      life: 100,
      reputation: 0,
      wins: 0,
      losses: 0,
      traits: ['brave'],
      price: 170,
    }),
    createMarketGladiator({
      id: 'market-demo-early-2',
      name: 'Sextus Celer',
      age: 21,
      strength: 8,
      agility: 4,
      defense: 6,
      life: 96,
      reputation: 0,
      wins: 0,
      losses: 0,
      traits: ['stoic'],
      price: 180,
    }),
    createMarketGladiator({
      id: 'market-demo-early-3',
      name: 'Marius Piso',
      age: 23,
      strength: 5,
      agility: 8,
      defense: 5,
      life: 90,
      reputation: 0,
      wins: 0,
      losses: 1,
      traits: ['lazy'],
      price: 150,
    }),
    createMarketGladiator({
      id: 'market-demo-early-4',
      name: 'Vibius Afer',
      age: 20,
      strength: 7,
      agility: 5,
      defense: 7,
      life: 97,
      reputation: 0,
      wins: 0,
      losses: 0,
      traits: ['disciplined'],
      price: 190,
    }),
    createMarketGladiator({
      id: 'market-demo-early-5',
      name: 'Atilius Crispus',
      age: 19,
      strength: 4,
      agility: 9,
      defense: 5,
      life: 92,
      reputation: 0,
      wins: 0,
      losses: 0,
      traits: ['cowardly'],
      price: 160,
    }),
  ],
});

export const demoEarlyLudus: DemoSaveDefinition = {
  id: 'demo-early-ludus',
  nameKey: 'demoSaves.early.name',
  descriptionKey: 'demoSaves.early.description',
  stageKey: 'demoSaves.stage.early',
  tags: ['demoSaves.tags.map', 'demoSaves.tags.beginner', 'demoSaves.tags.weeklyPlanning'],
  save,
  preferredRoute: 'ludus',
  preferredCameraTarget: 'ludus',
};
