import type { DemoSaveDefinition } from './types';
import {
  createBettingOdds,
  createDemoSave,
  createMarketGladiator,
  createPurchasedBuilding,
} from './demo-save-builders';

const year = 5;
const week = 7;
const createdAtDay = 'saturday';

const save = createDemoSave({
  id: 'demo-advanced-ludus',
  ownerName: 'Tiberius Cassianus',
  ludusName: 'Ludus Invictus',
  ludus: {
    treasury: 12000,
    reputation: 450,
  },
  time: {
    year,
    week,
    dayOfWeek: createdAtDay,
    hour: 18,
    minute: 30,
    speed: 0,
    isPaused: true,
  },
  buildings: {
    domus: createPurchasedBuilding({
      id: 'domus',
      level: 8,
    }),
    canteen: createPurchasedBuilding({
      id: 'canteen',
      level: 8,
      configuration: {
        mealPlanId: 'richMeals',
      },
      purchasedImprovementIds: ['betterKitchen', 'proteinRations', 'grainStorage'],
      selectedPolicyId: 'richMeals',
    }),
    dormitory: createPurchasedBuilding({
      id: 'dormitory',
      level: 8,
      configuration: {
        purchasedBeds: 12,
      },
      purchasedImprovementIds: ['strawBeds', 'woodenBeds', 'quietQuarters'],
    }),
    trainingGround: createPurchasedBuilding({
      id: 'trainingGround',
      level: 8,
      configuration: {
        defaultDoctrineId: 'brutalDiscipline',
      },
      purchasedImprovementIds: ['woodenWeapons', 'sparringRing', 'advancedDoctoreTools'],
      selectedPolicyId: 'brutalDiscipline',
    }),
    pleasureHall: createPurchasedBuilding({
      id: 'pleasureHall',
      level: 8,
      configuration: {
        entertainmentPlanId: 'grandEntertainment',
      },
      purchasedImprovementIds: ['gameTables', 'musicians', 'privateRooms'],
      selectedPolicyId: 'grandEntertainment',
    }),
    infirmary: createPurchasedBuilding({
      id: 'infirmary',
      level: 8,
      configuration: {
        carePolicyId: 'intensiveTreatment',
      },
      purchasedImprovementIds: ['cleanBandages', 'herbalStock', 'surgicalTools'],
      selectedPolicyId: 'intensiveTreatment',
    }),
  },
  gladiators: [
    {
      id: 'glad-demo-adv-maximus',
      name: 'Maximus Drusus',
      age: 34,
      strength: 78,
      agility: 61,
      defense: 72,
      energy: 88,
      health: 96,
      morale: 92,
      satiety: 84,
      reputation: 610,
      wins: 34,
      losses: 6,
      traits: ['crowdFavorite', 'stoic'],
      currentBuildingId: 'pleasureHall',
      weeklyObjective: 'protectChampion',
      combatStrategy: 'defensive',
    },
    {
      id: 'glad-demo-adv-severus',
      name: 'Severus Thrax',
      age: 29,
      strength: 84,
      agility: 48,
      defense: 63,
      energy: 66,
      health: 78,
      morale: 73,
      satiety: 70,
      reputation: 420,
      wins: 25,
      losses: 8,
      traits: ['brave'],
      currentBuildingId: 'trainingGround',
      weeklyObjective: 'fightPreparation',
      combatStrategy: 'aggressive',
    },
    {
      id: 'glad-demo-adv-cassian',
      name: 'Cassian Lupus',
      age: 23,
      strength: 54,
      agility: 82,
      defense: 44,
      energy: 72,
      health: 81,
      morale: 68,
      satiety: 77,
      reputation: 310,
      wins: 18,
      losses: 5,
      traits: ['ambitious'],
      currentBuildingId: 'trainingGround',
      weeklyObjective: 'trainAgility',
      combatStrategy: 'evasive',
    },
    {
      id: 'glad-demo-adv-brutus',
      name: 'Brutus Varro',
      age: 41,
      strength: 70,
      agility: 38,
      defense: 80,
      energy: 52,
      health: 74,
      morale: 61,
      satiety: 69,
      reputation: 280,
      wins: 20,
      losses: 11,
      traits: ['disciplined'],
      currentBuildingId: 'dormitory',
      weeklyObjective: 'recovery',
      intensity: 'light',
      combatStrategy: 'protectInjury',
    },
    {
      id: 'glad-demo-adv-nasica',
      name: 'Nasica Rufus',
      age: 27,
      strength: 48,
      agility: 57,
      defense: 69,
      energy: 90,
      health: 88,
      morale: 79,
      satiety: 82,
      reputation: 190,
      wins: 13,
      losses: 6,
      traits: ['stoic'],
      currentBuildingId: 'trainingGround',
      weeklyObjective: 'trainDefense',
      combatStrategy: 'defensive',
    },
    {
      id: 'glad-demo-adv-syrianus',
      name: 'Syrianus Afer',
      age: 22,
      strength: 61,
      agility: 65,
      defense: 50,
      energy: 38,
      health: 63,
      morale: 47,
      satiety: 55,
      reputation: 150,
      wins: 9,
      losses: 7,
      traits: ['rivalrous'],
      currentBuildingId: 'dormitory',
      weeklyObjective: 'fightPreparation',
      combatStrategy: 'exhaustOpponent',
    },
    {
      id: 'glad-demo-adv-cato',
      name: 'Cato Minor',
      age: 36,
      strength: 58,
      agility: 44,
      defense: 76,
      energy: 44,
      health: 39,
      morale: 58,
      satiety: 73,
      reputation: 225,
      wins: 15,
      losses: 9,
      traits: ['fragile'],
      currentBuildingId: 'infirmary',
      weeklyObjective: 'recovery',
      intensity: 'light',
      combatStrategy: 'protectInjury',
    },
    {
      id: 'glad-demo-adv-felix',
      name: 'Felix Murena',
      age: 20,
      strength: 42,
      agility: 50,
      defense: 36,
      energy: 82,
      health: 91,
      morale: 85,
      satiety: 88,
      reputation: 95,
      wins: 7,
      losses: 2,
      traits: ['crowdFavorite'],
      currentBuildingId: 'canteen',
      weeklyObjective: 'prepareForSale',
    },
  ],
  market: [
    createMarketGladiator({
      id: 'market-demo-advanced-1',
      name: 'Vettius Corax',
      age: 28,
      strength: 48,
      agility: 45,
      defense: 54,
      energy: 96,
      health: 98,
      morale: 78,
      satiety: 82,
      reputation: 160,
      wins: 12,
      losses: 4,
      traits: ['disciplined'],
      price: 1180,
    }),
    createMarketGladiator({
      id: 'market-demo-advanced-2',
      name: 'Lucanus Ferox',
      age: 31,
      strength: 64,
      agility: 38,
      defense: 50,
      energy: 92,
      health: 94,
      morale: 72,
      satiety: 80,
      reputation: 210,
      wins: 16,
      losses: 7,
      traits: ['brave'],
      price: 1420,
    }),
    createMarketGladiator({
      id: 'market-demo-advanced-3',
      name: 'Marcellus Vindex',
      age: 24,
      strength: 42,
      agility: 68,
      defense: 39,
      energy: 100,
      health: 90,
      morale: 76,
      satiety: 83,
      reputation: 180,
      wins: 14,
      losses: 3,
      traits: ['ambitious'],
      price: 1340,
    }),
    createMarketGladiator({
      id: 'market-demo-advanced-4',
      name: 'Numerius Scaeva',
      age: 35,
      strength: 52,
      agility: 40,
      defense: 66,
      energy: 88,
      health: 91,
      morale: 74,
      satiety: 79,
      reputation: 240,
      wins: 19,
      losses: 9,
      traits: ['stoic'],
      price: 1510,
    }),
    createMarketGladiator({
      id: 'market-demo-advanced-5',
      name: 'Appius Lupicinus',
      age: 26,
      strength: 55,
      agility: 55,
      defense: 48,
      energy: 94,
      health: 95,
      morale: 80,
      satiety: 85,
      reputation: 195,
      wins: 15,
      losses: 5,
      traits: ['crowdFavorite'],
      price: 1460,
    }),
  ],
  bettingOdds: [
    createBettingOdds({
      year,
      week,
      gladiatorId: 'glad-demo-adv-maximus',
      opponent: {
        id: 'opponent-demo-adv-maximus',
        name: 'Acer Germanus',
        age: 33,
        strength: 80,
        agility: 58,
        defense: 70,
        energy: 100,
        health: 100,
        morale: 78,
        satiety: 82,
        reputation: 560,
        wins: 0,
        losses: 0,
        traits: [],
      },
      rank: 'gold2',
      playerWinChance: 0.57,
      playerDecimalOdds: 1.65,
      opponentDecimalOdds: 2.18,
      createdAtDay,
    }),
    createBettingOdds({
      year,
      week,
      gladiatorId: 'glad-demo-adv-severus',
      opponent: {
        id: 'opponent-demo-adv-severus',
        name: 'Bato Silures',
        age: 30,
        strength: 78,
        agility: 50,
        defense: 61,
        energy: 100,
        health: 100,
        morale: 78,
        satiety: 82,
        reputation: 420,
        wins: 0,
        losses: 0,
        traits: [],
      },
      rank: 'silver3',
      playerWinChance: 0.53,
      playerDecimalOdds: 1.78,
      opponentDecimalOdds: 2,
      createdAtDay,
    }),
    createBettingOdds({
      year,
      week,
      gladiatorId: 'glad-demo-adv-cassian',
      opponent: {
        id: 'opponent-demo-adv-cassian',
        name: 'Cotys Velox',
        age: 25,
        strength: 56,
        agility: 78,
        defense: 45,
        energy: 100,
        health: 100,
        morale: 78,
        satiety: 82,
        reputation: 320,
        wins: 0,
        losses: 0,
        traits: [],
      },
      rank: 'bronze3',
      playerWinChance: 0.51,
      playerDecimalOdds: 1.85,
      opponentDecimalOdds: 1.92,
      createdAtDay,
    }),
    createBettingOdds({
      year,
      week,
      gladiatorId: 'glad-demo-adv-brutus',
      opponent: {
        id: 'opponent-demo-adv-brutus',
        name: 'Soranus Murena',
        age: 34,
        strength: 68,
        agility: 42,
        defense: 78,
        energy: 100,
        health: 100,
        morale: 78,
        satiety: 82,
        reputation: 280,
        wins: 0,
        losses: 0,
        traits: [],
      },
      rank: 'bronze3',
      playerWinChance: 0.46,
      playerDecimalOdds: 2.05,
      opponentDecimalOdds: 1.75,
      createdAtDay,
    }),
    createBettingOdds({
      year,
      week,
      gladiatorId: 'glad-demo-adv-nasica',
      opponent: {
        id: 'opponent-demo-adv-nasica',
        name: 'Sabinus Draco',
        age: 29,
        strength: 52,
        agility: 54,
        defense: 64,
        energy: 100,
        health: 100,
        morale: 78,
        satiety: 82,
        reputation: 190,
        wins: 0,
        losses: 0,
        traits: [],
      },
      rank: 'bronze3',
      playerWinChance: 0.54,
      playerDecimalOdds: 1.74,
      opponentDecimalOdds: 2.04,
      createdAtDay,
    }),
    createBettingOdds({
      year,
      week,
      gladiatorId: 'glad-demo-adv-syrianus',
      opponent: {
        id: 'opponent-demo-adv-syrianus',
        name: 'Juba Nigrinus',
        age: 24,
        strength: 60,
        agility: 66,
        defense: 52,
        energy: 100,
        health: 100,
        morale: 78,
        satiety: 82,
        reputation: 150,
        wins: 0,
        losses: 0,
        traits: [],
      },
      rank: 'bronze3',
      playerWinChance: 0.43,
      playerDecimalOdds: 2.19,
      opponentDecimalOdds: 1.65,
      createdAtDay,
    }),
    createBettingOdds({
      year,
      week,
      gladiatorId: 'glad-demo-adv-cato',
      opponent: {
        id: 'opponent-demo-adv-cato',
        name: 'Ferox Marsus',
        age: 37,
        strength: 60,
        agility: 46,
        defense: 72,
        energy: 100,
        health: 100,
        morale: 78,
        satiety: 82,
        reputation: 225,
        wins: 0,
        losses: 0,
        traits: [],
      },
      rank: 'bronze3',
      playerWinChance: 0.36,
      playerDecimalOdds: 2.61,
      opponentDecimalOdds: 1.47,
      createdAtDay,
    }),
    createBettingOdds({
      year,
      week,
      gladiatorId: 'glad-demo-adv-felix',
      opponent: {
        id: 'opponent-demo-adv-felix',
        name: 'Crispus Minor',
        age: 22,
        strength: 44,
        agility: 52,
        defense: 36,
        energy: 100,
        health: 100,
        morale: 78,
        satiety: 82,
        reputation: 95,
        wins: 0,
        losses: 0,
        traits: [],
      },
      rank: 'bronze3',
      playerWinChance: 0.52,
      playerDecimalOdds: 1.81,
      opponentDecimalOdds: 1.96,
      createdAtDay,
    }),
  ],
});

export const demoAdvancedLudus: DemoSaveDefinition = {
  id: 'demo-advanced-ludus',
  nameKey: 'demoSaves.advanced.name',
  descriptionKey: 'demoSaves.advanced.description',
  stageKey: 'demoSaves.stage.advanced',
  tags: ['demoSaves.tags.denseRoster', 'demoSaves.tags.betting', 'demoSaves.tags.dusk'],
  save,
  preferredRoute: 'ludus',
  preferredCameraTarget: 'arena',
};
