import type { DemoSaveDefinition } from './types';
import {
  createDemoSave,
  createMarketGladiator,
  createPurchasedBuilding,
} from './demo-save-builders';

const save = createDemoSave({
  id: 'demo-early-ludus',
  ludusName: 'Ludus Primus',
  ludus: {
    treasury: 850,
    reputation: 5,
  },
  time: {
    year: 1,
    week: 1,
    dayOfWeek: 'monday',
  },
  buildings: {
    domus: createPurchasedBuilding({
      id: 'domus',
      level: 3,
    }),
    canteen: createPurchasedBuilding({
      id: 'canteen',
      level: 1,
    }),
    dormitory: createPurchasedBuilding({
      id: 'dormitory',
      level: 1,
    }),
    trainingGround: createPurchasedBuilding({
      id: 'trainingGround',
      level: 1,
      configuration: {
        defaultDoctrineId: 'balancedTraining',
      },
      selectedPolicyId: 'balancedTraining',
    }),
  },
  gladiators: [
    {
      id: 'glad-demo-early-marcus',
      name: 'Marcus Varro',
      age: 19,
      experience: 0,
      strength: 3,
      agility: 3,
      defense: 2,
      life: 2,
      reputation: 0,
      wins: 0,
      losses: 0,
      traits: ['ambitious'],
    },
    {
      id: 'glad-demo-early-titus',
      name: 'Titus Marcellus',
      age: 18,
      experience: 0,
      strength: 2,
      agility: 2,
      defense: 4,
      life: 2,
      reputation: 10,
      wins: 1,
      losses: 0,
      traits: ['disciplined'],
    },
    {
      id: 'glad-demo-early-darius',
      name: 'Darius Nerva',
      age: 20,
      experience: 0,
      strength: 4,
      agility: 2,
      defense: 2,
      life: 2,
      reputation: 0,
      wins: 0,
      losses: 1,
      traits: ['fragile'],
    },
  ],
  market: [
    createMarketGladiator({
      id: 'market-demo-early-1',
      name: 'Nero Silvanus',
      age: 18,
      experience: 0,
      strength: 3,
      agility: 3,
      defense: 2,
      life: 2,
      reputation: 0,
      wins: 0,
      losses: 0,
      traits: ['brave'],
      price: 300,
    }),
    createMarketGladiator({
      id: 'market-demo-early-2',
      name: 'Sextus Celer',
      age: 21,
      experience: 0,
      strength: 4,
      agility: 2,
      defense: 2,
      life: 2,
      reputation: 0,
      wins: 0,
      losses: 0,
      traits: ['stoic'],
      price: 300,
    }),
    createMarketGladiator({
      id: 'market-demo-early-3',
      name: 'Marius Piso',
      age: 23,
      experience: 0,
      strength: 2,
      agility: 4,
      defense: 2,
      life: 2,
      reputation: 0,
      wins: 0,
      losses: 1,
      traits: ['lazy'],
      price: 300,
    }),
    createMarketGladiator({
      id: 'market-demo-early-4',
      name: 'Vibius Afer',
      age: 20,
      experience: 0,
      strength: 3,
      agility: 2,
      defense: 3,
      life: 2,
      reputation: 0,
      wins: 0,
      losses: 0,
      traits: ['disciplined'],
      price: 300,
    }),
    createMarketGladiator({
      id: 'market-demo-early-5',
      name: 'Atilius Crispus',
      age: 19,
      experience: 0,
      strength: 2,
      agility: 4,
      defense: 2,
      life: 2,
      reputation: 0,
      wins: 0,
      losses: 0,
      traits: ['cowardly'],
      price: 300,
    }),
  ],
});

export const demoEarlyLudus: DemoSaveDefinition = {
  id: 'demo-early-ludus',
  nameKey: 'demoSaves.early.name',
  descriptionKey: 'demoSaves.early.description',
  stageKey: 'demoSaves.stage.early',
  tags: ['demoSaves.tags.map', 'demoSaves.tags.beginner', 'demoSaves.tags.weeklyPlanning'],
  save,
  preferredRoute: 'ludus',
  preferredCameraTarget: 'ludus',
};
