import type { DemoSaveDefinition } from './types';
import {
  createBettingOdds,
  createDemoSave,
  createMarketGladiator,
  createPurchasedBuilding,
} from './demo-save-builders';

const year = 2;
const week = 4;
const createdAtDay = 'thursday';

const save = createDemoSave({
  id: 'demo-mid-ludus',
  ludusName: 'Ludus Ferrata',
  ludus: {
    treasury: 3200,
    reputation: 85,
  },
  time: {
    year,
    week,
    dayOfWeek: createdAtDay,
    hour: 16,
    minute: 0,
    speed: 0,
    isPaused: true,
  },
  buildings: {
    domus: createPurchasedBuilding({
      id: 'domus',
      level: 4,
    }),
    canteen: createPurchasedBuilding({
      id: 'canteen',
      level: 3,
      configuration: {
        mealPlanId: 'proteinFocusedMeals',
      },
      purchasedImprovementIds: ['betterKitchen', 'proteinRations'],
      selectedPolicyId: 'proteinFocusedMeals',
    }),
    dormitory: createPurchasedBuilding({
      id: 'dormitory',
      level: 4,
      purchasedImprovementIds: ['strawBeds', 'woodenBeds', 'quietQuarters'],
    }),
    trainingGround: createPurchasedBuilding({
      id: 'trainingGround',
      level: 4,
      configuration: {
        defaultDoctrineId: 'strengthDoctrine',
      },
      purchasedImprovementIds: ['sparringRing', 'advancedDoctoreTools'],
      selectedPolicyId: 'strengthDoctrine',
    }),
    pleasureHall: createPurchasedBuilding({
      id: 'pleasureHall',
      level: 3,
      configuration: {
        entertainmentPlanId: 'gamesAndSongs',
      },
      purchasedImprovementIds: ['gameTables', 'musicians'],
      selectedPolicyId: 'gamesAndSongs',
    }),
    infirmary: createPurchasedBuilding({
      id: 'infirmary',
      level: 3,
      configuration: {
        carePolicyId: 'preventiveCare',
      },
      purchasedImprovementIds: ['cleanBandages', 'herbalStock'],
      selectedPolicyId: 'preventiveCare',
    }),
  },
  gladiators: [
    {
      id: 'glad-demo-mid-gaius',
      name: 'Gaius Flamma',
      age: 26,
      strength: 32,
      agility: 26,
      defense: 22,
      energy: 70,
      health: 88,
      morale: 80,
      satiety: 75,
      reputation: 70,
      wins: 6,
      losses: 2,
      traits: ['brave', 'crowdFavorite'],
      currentBuildingId: 'trainingGround',
      weeklyObjective: 'balanced',
    },
    {
      id: 'glad-demo-mid-aulus',
      name: 'Aulus Niger',
      age: 24,
      strength: 22,
      agility: 40,
      defense: 18,
      energy: 55,
      health: 68,
      morale: 50,
      satiety: 62,
      reputation: 45,
      wins: 4,
      losses: 3,
      traits: ['ambitious'],
      currentBuildingId: 'pleasureHall',
      weeklyObjective: 'moraleBoost',
    },
    {
      id: 'glad-demo-mid-quintus',
      name: 'Quintus Felix',
      age: 30,
      strength: 28,
      agility: 20,
      defense: 35,
      energy: 62,
      health: 95,
      morale: 90,
      satiety: 80,
      reputation: 120,
      wins: 10,
      losses: 4,
      traits: ['disciplined', 'stoic'],
      currentBuildingId: 'trainingGround',
      weeklyObjective: 'trainDefense',
    },
    {
      id: 'glad-demo-mid-publius',
      name: 'Publius Corvus',
      age: 21,
      strength: 18,
      agility: 18,
      defense: 24,
      energy: 80,
      health: 52,
      morale: 60,
      satiety: 58,
      reputation: 25,
      wins: 2,
      losses: 2,
      traits: ['fragile'],
      currentBuildingId: 'infirmary',
      weeklyObjective: 'recovery',
      intensity: 'light',
    },
  ],
  market: [
    createMarketGladiator({
      id: 'market-demo-mid-1',
      name: 'Servius Ruga',
      age: 24,
      strength: 20,
      agility: 18,
      defense: 21,
      energy: 96,
      health: 96,
      morale: 72,
      satiety: 78,
      reputation: 12,
      wins: 1,
      losses: 1,
      traits: ['stoic'],
      price: 360,
    }),
    createMarketGladiator({
      id: 'market-demo-mid-2',
      name: 'Lentulus Varo',
      age: 28,
      strength: 27,
      agility: 16,
      defense: 19,
      energy: 90,
      health: 88,
      morale: 66,
      satiety: 70,
      reputation: 25,
      wins: 3,
      losses: 2,
      traits: ['brave'],
      price: 430,
    }),
    createMarketGladiator({
      id: 'market-demo-mid-3',
      name: 'Hostus Naso',
      age: 22,
      strength: 18,
      agility: 29,
      defense: 16,
      energy: 95,
      health: 92,
      morale: 71,
      satiety: 74,
      reputation: 18,
      wins: 2,
      losses: 0,
      traits: ['ambitious'],
      price: 420,
    }),
    createMarketGladiator({
      id: 'market-demo-mid-4',
      name: 'Fabius Sura',
      age: 31,
      strength: 22,
      agility: 15,
      defense: 30,
      energy: 86,
      health: 93,
      morale: 69,
      satiety: 76,
      reputation: 40,
      wins: 5,
      losses: 5,
      traits: ['disciplined'],
      price: 500,
    }),
    createMarketGladiator({
      id: 'market-demo-mid-5',
      name: 'Tarquinius Balbus',
      age: 20,
      strength: 17,
      agility: 22,
      defense: 20,
      energy: 100,
      health: 97,
      morale: 76,
      satiety: 82,
      reputation: 8,
      wins: 1,
      losses: 0,
      traits: ['crowdFavorite'],
      price: 390,
    }),
  ],
  bettingOdds: [
    createBettingOdds({
      year,
      week,
      gladiatorId: 'glad-demo-mid-gaius',
      opponent: {
        id: 'opponent-demo-mid-gaius',
        name: 'Rufus Caldus',
        age: 27,
        strength: 30,
        agility: 24,
        defense: 20,
        energy: 100,
        health: 100,
        morale: 75,
        satiety: 80,
        reputation: 60,
        wins: 0,
        losses: 0,
        traits: [],
      },
      rank: 'bronze1',
      playerWinChance: 0.58,
      playerDecimalOdds: 1.62,
      opponentDecimalOdds: 2.24,
      createdAtDay,
    }),
    createBettingOdds({
      year,
      week,
      gladiatorId: 'glad-demo-mid-aulus',
      opponent: {
        id: 'opponent-demo-mid-aulus',
        name: 'Milo Cimber',
        age: 25,
        strength: 24,
        agility: 34,
        defense: 17,
        energy: 100,
        health: 100,
        morale: 75,
        satiety: 80,
        reputation: 50,
        wins: 0,
        losses: 0,
        traits: [],
      },
      rank: 'bronze2',
      playerWinChance: 0.49,
      playerDecimalOdds: 1.92,
      opponentDecimalOdds: 1.85,
      createdAtDay,
    }),
    createBettingOdds({
      year,
      week,
      gladiatorId: 'glad-demo-mid-quintus',
      opponent: {
        id: 'opponent-demo-mid-quintus',
        name: 'Decimus Falco',
        age: 32,
        strength: 31,
        agility: 19,
        defense: 34,
        energy: 100,
        health: 100,
        morale: 75,
        satiety: 80,
        reputation: 110,
        wins: 0,
        losses: 0,
        traits: [],
      },
      rank: 'silver3',
      playerWinChance: 0.55,
      playerDecimalOdds: 1.71,
      opponentDecimalOdds: 2.09,
      createdAtDay,
    }),
    createBettingOdds({
      year,
      week,
      gladiatorId: 'glad-demo-mid-publius',
      opponent: {
        id: 'opponent-demo-mid-publius',
        name: 'Otho Varus',
        age: 23,
        strength: 20,
        agility: 18,
        defense: 26,
        energy: 100,
        health: 100,
        morale: 75,
        satiety: 80,
        reputation: 30,
        wins: 0,
        losses: 0,
        traits: [],
      },
      rank: 'bronze3',
      playerWinChance: 0.42,
      playerDecimalOdds: 2.24,
      opponentDecimalOdds: 1.62,
      createdAtDay,
    }),
  ],
});

export const demoMidLudus: DemoSaveDefinition = {
  id: 'demo-mid-ludus',
  nameKey: 'demoSaves.mid.name',
  descriptionKey: 'demoSaves.mid.description',
  stageKey: 'demoSaves.stage.mid',
  tags: ['demoSaves.tags.market', 'demoSaves.tags.betting', 'demoSaves.tags.alerts'],
  save,
  preferredRoute: 'ludus',
  preferredCameraTarget: 'market',
};
