import type {
  BuildingEffect,
  BuildingId,
  BuildingSkillDefinition,
} from '../domain/buildings/types';
import { getBuildingActivityIdsBySkill } from './building-activities';

const skillNamesByBuilding = {
  domus: [
    'Ledger Room',
    'Contract Shelf',
    'Staff Registry',
    'Treasury Lockbox',
    'Reception Atrium',
    'Steward Desk',
    'Tax Planning',
    'Loan Contacts',
    'Weekly Board',
    'Patron Letters',
    'Profit Forecasting',
    'Legal Favors',
    'Recruitment Files',
    'Public Seal',
    'Debt Refinancing',
    'Political Network',
    'Grand Strategy',
    'Championship Booking',
    'Provincial Charter',
    'Legacy House',
  ],
  trainingGround: [
    'Wooden Pali',
    'Footwork Lines',
    'Basic Drills',
    'Endurance Runs',
    'Pair Sparring',
    'Weapon Rotation',
    'Shield Discipline',
    'Injury Awareness',
    'Veteran Demonstrations',
    'Noble Training',
    'Tactical Scenarios',
    'Class Specialization',
    'Fatigue Control',
    'Arena Simulation',
    'Soldier Training',
    'Elite Conditioning',
    'Champion Method',
    'Brutal Efficiency',
    'Master Trainer Doctrine',
    'Public Drill',
  ],
  canteen: [
    'Grain Stores',
    'Clean Water',
    'Soup Rotation',
    'Basic Hygiene',
    'Cook Assignment',
    'Protein Meals',
    'Herbal Broths',
    'Waste Control',
    'Feast Day',
    'Ration Ledger',
    'Performance Diet',
    'Recovery Meals',
    'Morale Banquets',
    'Disease Prevention',
    'Supply Contracts',
    'Champion Diet',
    'Luxury Imports',
    'Emergency Reserves',
    'Festival Catering',
    'Nutritional Doctrine',
  ],
  dormitory: [
    'Straw Bedding',
    'Clean Mats',
    'Quiet Rules',
    'Night Lamps',
    'Shared Quarters',
    'Wooden Beds',
    'Noise Screens',
    'Personal Chests',
    'Injury Rest Area',
    'Mood Rules',
    'Veteran Wing',
    'Champion Room',
    'Conflict Mediation',
    'Heat Management',
    'Loyalty Rituals',
    'Private Cells',
    'Brotherhood Oaths',
    'Rest Discipline',
    'Crisis Shelter',
    'Honor Hall',
  ],
  infirmary: [
    'Bandages',
    'Herb Shelf',
    'Clean Knives',
    'Injury Log',
    'Rest Orders',
    'Bone Setting',
    'Infection Control',
    'Pain Drafts',
    'Recovery Beds',
    'Field Triage',
    'Surgery Table',
    'Scar Treatment',
    'Disease Isolation',
    'Physio Training',
    'Blood Loss Protocol',
    'Master Medicus',
    'Experimental Remedies',
    'Champion Preservation',
    'Plague Procedure',
    'Death Prevention',
  ],
  guardBarracks: [
    'Gate Lock',
    'Patrol Route',
    'Guard Roster',
    'Torch Posts',
    'Weapon Rack',
    'Watchtower',
    'Visitor Checks',
    'Contraband Search',
    'Slave Count',
    'Alarm Bell',
    'Bribe Detection',
    'Riot Formation',
    'Escape Nets',
    'Night Watch',
    'Interrogation Room',
    'Praetorian Contract',
    'Iron Discipline',
    'Spy Network',
    'Crisis Lockdown',
    'Rebellion Protocol',
  ],
  pleasureHall: [
    'Dice Tables',
    'Music Corner',
    'Bath Basin',
    'Story Nights',
    'Garden Shade',
    'Games And Songs',
    'Private Rooms',
    'Poetry Evenings',
    'Reward Tokens',
    'Quiet Evenings',
    'Grand Entertainment',
    'Festival Stage',
    'Champion Toasts',
    'Conflict Relief',
    'Patron Visits',
    'Luxury Courtyard',
    'Public Feast',
    'Morale Doctrine',
    'Exotic Performers',
    'Reputation Salon',
  ],
  farm: [
    'Grain Field',
    'Olive Rows',
    'Goat Pen',
    'Water Ditch',
    'Slave Tools',
    'Crop Rotation',
    'Storage Barn',
    'Market Surplus',
    'Herbal Garden',
    'Irrigation',
    'High Yield Grain',
    'Livestock Expansion',
    'Preserved Food',
    'Trade Cart',
    'Estate Foreman',
    'Luxury Produce',
    'Emergency Granary',
    'Export Contracts',
    'Agricultural Doctrine',
    'Rural Patronage',
  ],
  armory: [
    'Repair Bench',
    'Basic Swords',
    'Shields',
    'Leather Armor',
    'Inventory Hooks',
    'Spear Rack',
    'Helmet Fitting',
    'Weapon Oil',
    'Armor Patching',
    'Quality Sorting',
    'Custom Gear',
    'Reinforced Shields',
    'Heavy Armor',
    'Exotic Weapons',
    'Quartermaster',
    'Master Smith',
    'Signature Weapons',
    'Arena Sets',
    'Legendary Repairs',
    'Equipment Doctrine',
  ],
  exhibitionGrounds: [
    'Sand Ring',
    'Practice Stands',
    'Crowd Fence',
    'Match Bell',
    'Blood Drain',
    'Local Exhibitions',
    'Announcer',
    'Mercy Signal',
    'Sponsor Seats',
    'Injury Crew',
    'Themed Shows',
    'Rival Ludus Events',
    'Crowd Control',
    'Champion Parade',
    'Public Lessons',
    'Regional Spectacle',
    'Fame Engine',
    'Grand Spectacle',
    'Arena Mastery',
    'Civic Festival',
  ],
  bookmakerOffice: [
    'Odds Ledger',
    'Betting Bench',
    'Trusted Clerk',
    'Guarded Box',
    'Payout Rules',
    'Public Odds',
    'Risk Limits',
    'Patron Bets',
    'Fraud Watch',
    'Debt Collection',
    'House Edge',
    'Insider Rumors',
    'Rival Lines',
    'High Roller Room',
    'Bribe Buffer',
    'Provincial Network',
    'Shadow Markets',
    'Championship Book',
    'Scandal Control',
    'Betting Empire',
  ],
  banquetHall: [
    'Long Tables',
    'Wine Stores',
    'Servant Routes',
    'Music Alcove',
    'Guest List',
    'Noble Dinner',
    'Victory Feast',
    'Merchant Supper',
    'Magistrate Seat',
    'Gift Protocol',
    'Political Banquet',
    'Luxury Menu',
    'Rival Invitation',
    'Patron Contract',
    'Reputation Toast',
    'Grand Feast',
    'Provincial Guests',
    'Favor Network',
    'Imperial Rumor',
    'Legendary Banquet',
  ],
  forgeWorkshop: [
    'Charcoal Pit',
    'Bellows',
    'Iron Stock',
    'Anvil Block',
    'Apprentice Smith',
    'Blade Molds',
    'Armor Rivets',
    'Repair Orders',
    'Trade Ingots',
    'Quality Stamp',
    'Weapon Contracts',
    'Shield Frames',
    'Exotic Metal',
    'Master Tempering',
    'Workshop Ledger',
    'Export Arms',
    'Signature Forge',
    'Legion Contract',
    'Legendary Steel',
    'Forge Doctrine',
  ],
} satisfies Record<BuildingId, readonly string[]>;

interface SkillEffectPattern {
  type: BuildingEffect['type'];
  target: NonNullable<BuildingEffect['target']>;
  values: readonly [number, number, number, number];
}

type SkillEffectPatternRow = readonly [
  SkillEffectPattern,
  SkillEffectPattern,
  SkillEffectPattern,
  SkillEffectPattern,
  SkillEffectPattern,
];

const skillEffectPatternsByBuilding = {
  domus: [
    { type: 'reduceExpense', target: 'ludus', values: [1, 1.5, 2, 2.5] },
    { type: 'increaseIncome', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseStaffEfficiency', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseReputation', target: 'ludus', values: [0.25, 0.5, 0.75, 1] },
    { type: 'decreaseRebellion', target: 'ludus', values: [0.5, 1, 1.5, 2] },
  ],
  trainingGround: [
    { type: 'increaseStrength', target: 'plannedGladiators', values: [1, 1.5, 2, 2.5] },
    { type: 'increaseAgility', target: 'plannedGladiators', values: [1, 1.5, 2, 2.5] },
    { type: 'increaseDefense', target: 'plannedGladiators', values: [1, 1.5, 2, 2.5] },
    { type: 'reduceInjuryRisk', target: 'allGladiators', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseReputation', target: 'ludus', values: [0.5, 1, 1.5, 2] },
  ],
  canteen: [
    { type: 'increaseHappiness', target: 'ludus', values: [1, 1.5, 2, 2.5] },
    { type: 'increaseLife', target: 'plannedGladiators', values: [1, 1.5, 2, 2.5] },
    { type: 'increaseIncome', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseProduction', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseHappiness', target: 'ludus', values: [1, 1.5, 2, 2.5] },
  ],
  dormitory: [
    { type: 'increaseHappiness', target: 'ludus', values: [1, 1.5, 2, 2.5] },
    { type: 'increaseReputation', target: 'ludus', values: [0.25, 0.5, 0.75, 1] },
    { type: 'decreaseRebellion', target: 'ludus', values: [1, 1.5, 2, 2.5] },
    { type: 'increaseLife', target: 'plannedGladiators', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseHappiness', target: 'ludus', values: [0.5, 1, 1.5, 2] },
  ],
  infirmary: [
    { type: 'increaseLife', target: 'plannedGladiators', values: [1, 1.5, 2, 2.5] },
    { type: 'reduceInjuryRisk', target: 'allGladiators', values: [1, 1.5, 2, 2.5] },
    { type: 'increaseStaffEfficiency', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseHappiness', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'decreaseRebellion', target: 'ludus', values: [0.5, 1, 1.5, 2] },
  ],
  guardBarracks: [
    { type: 'increaseSecurity', target: 'ludus', values: [1, 1.5, 2, 2.5] },
    { type: 'decreaseRebellion', target: 'ludus', values: [1, 1.5, 2, 2.5] },
    { type: 'reduceExpense', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseStaffEfficiency', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseSecurity', target: 'ludus', values: [1, 1.5, 2, 2.5] },
  ],
  farm: [
    { type: 'increaseProduction', target: 'ludus', values: [1, 1.5, 2, 2.5] },
    { type: 'increaseIncome', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'reduceExpense', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseLife', target: 'plannedGladiators', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseStaffEfficiency', target: 'ludus', values: [0.5, 1, 1.5, 2] },
  ],
  pleasureHall: [
    { type: 'increaseHappiness', target: 'ludus', values: [1, 1.5, 2, 2.5] },
    { type: 'increaseHappiness', target: 'ludus', values: [1, 1.5, 2, 2.5] },
    { type: 'increaseReputation', target: 'ludus', values: [0.25, 0.5, 0.75, 1] },
    { type: 'increaseIncome', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'decreaseRebellion', target: 'ludus', values: [0.5, 1, 1.5, 2] },
  ],
  exhibitionGrounds: [
    { type: 'increaseIncome', target: 'ludus', values: [1, 1.5, 2, 2.5] },
    { type: 'increaseReputation', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseReputation', target: 'ludus', values: [0.25, 0.5, 0.75, 1] },
    { type: 'increaseHappiness', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseSecurity', target: 'ludus', values: [0.5, 1, 1.5, 2] },
  ],
  armory: [
    { type: 'increaseStrength', target: 'plannedGladiators', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseDefense', target: 'plannedGladiators', values: [1, 1.5, 2, 2.5] },
    { type: 'reduceInjuryRisk', target: 'allGladiators', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseProduction', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseStaffEfficiency', target: 'ludus', values: [0.5, 1, 1.5, 2] },
  ],
  bookmakerOffice: [
    { type: 'increaseIncome', target: 'ludus', values: [1, 1.5, 2, 2.5] },
    { type: 'reduceExpense', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseSecurity', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseReputation', target: 'ludus', values: [0.25, 0.5, 0.75, 1] },
    { type: 'decreaseRebellion', target: 'ludus', values: [0.5, 1, 1.5, 2] },
  ],
  banquetHall: [
    { type: 'increaseReputation', target: 'ludus', values: [0.5, 0.75, 1, 1.25] },
    { type: 'increaseHappiness', target: 'ludus', values: [1, 1.5, 2, 2.5] },
    { type: 'increaseIncome', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'decreaseRebellion', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseReputation', target: 'ludus', values: [0.5, 1, 1.5, 2] },
  ],
  forgeWorkshop: [
    { type: 'increaseProduction', target: 'ludus', values: [1, 1.5, 2, 2.5] },
    { type: 'reduceExpense', target: 'ludus', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseStrength', target: 'plannedGladiators', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseDefense', target: 'plannedGladiators', values: [0.5, 1, 1.5, 2] },
    { type: 'increaseIncome', target: 'ludus', values: [0.5, 1, 1.5, 2] },
  ],
} satisfies Record<BuildingId, SkillEffectPatternRow>;

function createSkillEffect(
  buildingId: BuildingId,
  tier: number,
  tierPosition: number,
): BuildingEffect {
  const pattern = skillEffectPatternsByBuilding[buildingId][tierPosition];

  return {
    type: pattern.type,
    value: pattern.values[tier - 1],
    target: pattern.target,
  };
}

function slugify(name: string) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function createSkillTree(buildingId: BuildingId, names: readonly string[]) {
  const firstTierSkillIds = names.slice(0, 5).map((name) => `${buildingId}.${slugify(name)}`);
  const firstSecondTierSkillId = `${buildingId}.${slugify(names[5])}`;
  const firstThirdTierSkillId = `${buildingId}.${slugify(names[10])}`;

  return names.map((name, index): BuildingSkillDefinition => {
    const tier = Math.floor(index / 5) + 1;
    const id = `${buildingId}.${slugify(name)}`;
    const requiredSkillIds =
      tier === 1
        ? undefined
        : tier === 2
          ? firstTierSkillIds.slice(0, 3)
          : tier === 3
            ? [firstSecondTierSkillId]
            : [firstThirdTierSkillId];

    return {
      id,
      buildingId,
      tier,
      name,
      nameKey: 'buildingSkills.skillName',
      descriptionKey: `buildingSkills.${id}.description`,
      cost: tier * 90,
      requiredBuildingLevel: tier <= 2 ? 1 : tier === 3 ? 3 : 5,
      requiredSkillIds,
      effects: [createSkillEffect(buildingId, tier, index % 5)],
      unlockedActivities: getBuildingActivityIdsBySkill(id),
    };
  });
}

export const BUILDING_SKILLS: BuildingSkillDefinition[] = Object.entries(skillNamesByBuilding)
  .flatMap(([buildingId, names]) => createSkillTree(buildingId as BuildingId, names))
  .sort((left, right) => left.buildingId.localeCompare(right.buildingId) || left.tier - right.tier);

export function getBuildingSkills(buildingId: BuildingId) {
  return BUILDING_SKILLS.filter((skill) => skill.buildingId === buildingId);
}
