import type {
  BuildingImprovementDefinition,
  BuildingPolicyDefinition,
} from '../domain/buildings/types';

export const BUILDING_IMPROVEMENTS: BuildingImprovementDefinition[] = [
  {
    id: 'betterKitchen',
    buildingId: 'canteen',
    nameKey: 'improvements.betterKitchen.name',
    descriptionKey: 'improvements.betterKitchen.description',
    cost: 90,
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseSatiety', value: 2, target: 'assignedGladiator' }],
  },
  {
    id: 'proteinRations',
    buildingId: 'canteen',
    nameKey: 'improvements.proteinRations.name',
    descriptionKey: 'improvements.proteinRations.description',
    cost: 130,
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseStrength', value: 1, target: 'assignedGladiator' }],
  },
  {
    id: 'grainStorage',
    buildingId: 'canteen',
    nameKey: 'improvements.grainStorage.name',
    descriptionKey: 'improvements.grainStorage.description',
    cost: 110,
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseSatiety', value: 1, target: 'allGladiators' }],
  },
  {
    id: 'strawBeds',
    buildingId: 'dormitory',
    nameKey: 'improvements.strawBeds.name',
    descriptionKey: 'improvements.strawBeds.description',
    cost: 70,
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseCapacity', value: 1, target: 'ludus' }],
  },
  {
    id: 'woodenBeds',
    buildingId: 'dormitory',
    nameKey: 'improvements.woodenBeds.name',
    descriptionKey: 'improvements.woodenBeds.description',
    cost: 130,
    requiredBuildingLevel: 1,
    requiredImprovementIds: ['strawBeds'],
    effects: [{ type: 'increaseEnergy', value: 2, target: 'assignedGladiator' }],
  },
  {
    id: 'quietQuarters',
    buildingId: 'dormitory',
    nameKey: 'improvements.quietQuarters.name',
    descriptionKey: 'improvements.quietQuarters.description',
    cost: 150,
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseMorale', value: 1, target: 'assignedGladiator' }],
  },
  {
    id: 'woodenWeapons',
    buildingId: 'trainingGround',
    nameKey: 'improvements.woodenWeapons.name',
    descriptionKey: 'improvements.woodenWeapons.description',
    cost: 100,
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseReadiness', value: 2, target: 'assignedGladiator' }],
  },
  {
    id: 'sparringRing',
    buildingId: 'trainingGround',
    nameKey: 'improvements.sparringRing.name',
    descriptionKey: 'improvements.sparringRing.description',
    cost: 160,
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseAgility', value: 1, target: 'assignedGladiator' }],
  },
  {
    id: 'advancedDoctoreTools',
    buildingId: 'trainingGround',
    nameKey: 'improvements.advancedDoctoreTools.name',
    descriptionKey: 'improvements.advancedDoctoreTools.description',
    cost: 220,
    requiredBuildingLevel: 2,
    effects: [{ type: 'reduceInjuryRisk', value: 3, target: 'assignedGladiator' }],
  },
  {
    id: 'gameTables',
    buildingId: 'pleasureHall',
    nameKey: 'improvements.gameTables.name',
    descriptionKey: 'improvements.gameTables.description',
    cost: 90,
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseMorale', value: 2, target: 'assignedGladiator' }],
  },
  {
    id: 'musicians',
    buildingId: 'pleasureHall',
    nameKey: 'improvements.musicians.name',
    descriptionKey: 'improvements.musicians.description',
    cost: 160,
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseMorale', value: 1, target: 'allGladiators' }],
  },
  {
    id: 'privateRooms',
    buildingId: 'pleasureHall',
    nameKey: 'improvements.privateRooms.name',
    descriptionKey: 'improvements.privateRooms.description',
    cost: 210,
    requiredBuildingLevel: 2,
    effects: [{ type: 'increaseReadiness', value: 3, target: 'assignedGladiator' }],
  },
  {
    id: 'cleanBandages',
    buildingId: 'infirmary',
    nameKey: 'improvements.cleanBandages.name',
    descriptionKey: 'improvements.cleanBandages.description',
    cost: 100,
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseHealth', value: 2, target: 'assignedGladiator' }],
  },
  {
    id: 'herbalStock',
    buildingId: 'infirmary',
    nameKey: 'improvements.herbalStock.name',
    descriptionKey: 'improvements.herbalStock.description',
    cost: 150,
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseHealth', value: 1, target: 'allGladiators' }],
  },
  {
    id: 'surgicalTools',
    buildingId: 'infirmary',
    nameKey: 'improvements.surgicalTools.name',
    descriptionKey: 'improvements.surgicalTools.description',
    cost: 240,
    requiredBuildingLevel: 2,
    effects: [{ type: 'reduceInjuryRisk', value: 8, target: 'allGladiators' }],
  },
];

export const BUILDING_POLICIES: BuildingPolicyDefinition[] = [
  {
    id: 'economicalMeals',
    buildingId: 'canteen',
    nameKey: 'policies.economicalMeals.name',
    descriptionKey: 'policies.economicalMeals.description',
    requiredBuildingLevel: 1,
    effects: [
      { type: 'increaseSatiety', value: 3, target: 'assignedGladiator' },
      { type: 'decreaseMorale', value: 1, target: 'assignedGladiator' },
    ],
    cost: 10,
  },
  {
    id: 'balancedMeals',
    buildingId: 'canteen',
    nameKey: 'policies.balancedMeals.name',
    descriptionKey: 'policies.balancedMeals.description',
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseSatiety', value: 5, target: 'assignedGladiator' }],
    cost: 20,
  },
  {
    id: 'richMeals',
    buildingId: 'canteen',
    nameKey: 'policies.richMeals.name',
    descriptionKey: 'policies.richMeals.description',
    requiredBuildingLevel: 1,
    effects: [
      { type: 'increaseSatiety', value: 7, target: 'assignedGladiator' },
      { type: 'increaseMorale', value: 1, target: 'assignedGladiator' },
    ],
    cost: 40,
  },
  {
    id: 'proteinFocusedMeals',
    buildingId: 'canteen',
    nameKey: 'policies.proteinFocusedMeals.name',
    descriptionKey: 'policies.proteinFocusedMeals.description',
    requiredBuildingLevel: 1,
    effects: [
      { type: 'increaseSatiety', value: 4, target: 'assignedGladiator' },
      { type: 'increaseStrength', value: 1, target: 'assignedGladiator' },
    ],
    cost: 30,
  },
  {
    id: 'balancedTraining',
    buildingId: 'trainingGround',
    nameKey: 'policies.balancedTraining.name',
    descriptionKey: 'policies.balancedTraining.description',
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseReadiness', value: 1, target: 'assignedGladiator' }],
  },
  {
    id: 'strengthDoctrine',
    buildingId: 'trainingGround',
    nameKey: 'policies.strengthDoctrine.name',
    descriptionKey: 'policies.strengthDoctrine.description',
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseStrength', value: 1, target: 'assignedGladiator' }],
  },
  {
    id: 'agilityDoctrine',
    buildingId: 'trainingGround',
    nameKey: 'policies.agilityDoctrine.name',
    descriptionKey: 'policies.agilityDoctrine.description',
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseAgility', value: 1, target: 'assignedGladiator' }],
  },
  {
    id: 'defensiveDoctrine',
    buildingId: 'trainingGround',
    nameKey: 'policies.defensiveDoctrine.name',
    descriptionKey: 'policies.defensiveDoctrine.description',
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseDefense', value: 1, target: 'assignedGladiator' }],
  },
  {
    id: 'brutalDiscipline',
    buildingId: 'trainingGround',
    nameKey: 'policies.brutalDiscipline.name',
    descriptionKey: 'policies.brutalDiscipline.description',
    requiredBuildingLevel: 2,
    effects: [
      { type: 'increaseStrength', value: 2, target: 'assignedGladiator' },
      { type: 'decreaseMorale', value: 2, target: 'assignedGladiator' },
    ],
  },
  {
    id: 'quietEvenings',
    buildingId: 'pleasureHall',
    nameKey: 'policies.quietEvenings.name',
    descriptionKey: 'policies.quietEvenings.description',
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseMorale', value: 3, target: 'assignedGladiator' }],
  },
  {
    id: 'gamesAndSongs',
    buildingId: 'pleasureHall',
    nameKey: 'policies.gamesAndSongs.name',
    descriptionKey: 'policies.gamesAndSongs.description',
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseMorale', value: 5, target: 'assignedGladiator' }],
    cost: 25,
  },
  {
    id: 'grandEntertainment',
    buildingId: 'pleasureHall',
    nameKey: 'policies.grandEntertainment.name',
    descriptionKey: 'policies.grandEntertainment.description',
    requiredBuildingLevel: 2,
    effects: [{ type: 'increaseMorale', value: 8, target: 'allGladiators' }],
    cost: 60,
  },
  {
    id: 'basicCare',
    buildingId: 'infirmary',
    nameKey: 'policies.basicCare.name',
    descriptionKey: 'policies.basicCare.description',
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseHealth', value: 3, target: 'assignedGladiator' }],
  },
  {
    id: 'preventiveCare',
    buildingId: 'infirmary',
    nameKey: 'policies.preventiveCare.name',
    descriptionKey: 'policies.preventiveCare.description',
    requiredBuildingLevel: 1,
    effects: [{ type: 'reduceInjuryRisk', value: 4, target: 'allGladiators' }],
    cost: 30,
  },
  {
    id: 'intensiveTreatment',
    buildingId: 'infirmary',
    nameKey: 'policies.intensiveTreatment.name',
    descriptionKey: 'policies.intensiveTreatment.description',
    requiredBuildingLevel: 2,
    effects: [{ type: 'increaseHealth', value: 8, target: 'assignedGladiator' }],
    cost: 70,
  },
];
