import type { MapRect } from './map-layout';
import { VISUAL_ASSET_MANIFEST } from './visual-assets';

export type MapAmbientElementKind = 'cloud' | 'grass' | 'banner' | 'torch' | 'smoke' | 'crowd';

export interface MapAmbientElementDefinition extends MapRect {
  id: string;
  kind: MapAmbientElementKind;
  assetPath: string;
  rotation?: number;
  scale?: number;
  opacity?: number;
  animationDelaySeconds?: number;
  animationDurationSeconds?: number;
  zIndex?: number;
}

export interface MapWaterAnimationDefinition extends MapRect {
  id: string;
  color: string;
  lineCount: number;
  lineWidth: number;
  opacity: number;
  speed: number;
}

const ambientAssets = VISUAL_ASSET_MANIFEST.map.ambient;

export const LUDUS_MAP_WATER_ANIMATION: MapWaterAnimationDefinition = {
  id: 'coastal-sea',
  x: 760,
  y: 150,
  width: 2140,
  height: 390,
  color: '#d8f6ff',
  lineCount: 18,
  lineWidth: 3,
  opacity: 0.18,
  speed: 0.22,
};

export const LUDUS_MAP_AMBIENT_ELEMENTS: MapAmbientElementDefinition[] = [
  {
    id: 'cloud-west-long',
    kind: 'cloud',
    assetPath: ambientAssets['cloud-01'],
    x: -360,
    y: 94,
    width: 286,
    height: 128,
    opacity: 0.62,
    scale: 1.08,
    animationDelaySeconds: -24,
    animationDurationSeconds: 98,
    zIndex: 0,
  },
  {
    id: 'cloud-central-soft',
    kind: 'cloud',
    assetPath: ambientAssets['cloud-02'],
    x: -520,
    y: 210,
    width: 230,
    height: 104,
    opacity: 0.48,
    scale: 0.9,
    animationDelaySeconds: -66,
    animationDurationSeconds: 124,
    zIndex: 0,
  },
  {
    id: 'cloud-east-high',
    kind: 'cloud',
    assetPath: ambientAssets['cloud-01'],
    x: -260,
    y: 48,
    width: 196,
    height: 88,
    opacity: 0.42,
    scale: 0.78,
    animationDelaySeconds: -12,
    animationDurationSeconds: 136,
    zIndex: 0,
  },
  {
    id: 'grass-market-road',
    kind: 'grass',
    assetPath: ambientAssets['grass-tuft-01'],
    x: 480,
    y: 900,
    width: 42,
    height: 42,
    rotation: -6,
    opacity: 0.84,
    animationDelaySeconds: -0.8,
    animationDurationSeconds: 3.8,
    zIndex: 3,
  },
  {
    id: 'grass-courtyard-west',
    kind: 'grass',
    assetPath: ambientAssets['grass-tuft-01'],
    x: 900,
    y: 780,
    width: 34,
    height: 34,
    rotation: 5,
    opacity: 0.78,
    animationDelaySeconds: -1.7,
    animationDurationSeconds: 4.4,
    zIndex: 3,
  },
  {
    id: 'grass-domus-path',
    kind: 'grass',
    assetPath: ambientAssets['grass-tuft-01'],
    x: 1325,
    y: 815,
    width: 38,
    height: 38,
    rotation: 8,
    opacity: 0.8,
    animationDelaySeconds: -2.4,
    animationDurationSeconds: 4.1,
    zIndex: 3,
  },
  {
    id: 'grass-training-fence',
    kind: 'grass',
    assetPath: ambientAssets['grass-tuft-01'],
    x: 1668,
    y: 1036,
    width: 46,
    height: 46,
    rotation: -3,
    opacity: 0.82,
    animationDelaySeconds: -3.1,
    animationDurationSeconds: 5,
    zIndex: 3,
  },
  {
    id: 'grass-arena-road',
    kind: 'grass',
    assetPath: ambientAssets['grass-tuft-01'],
    x: 1848,
    y: 655,
    width: 36,
    height: 36,
    rotation: 9,
    opacity: 0.72,
    animationDelaySeconds: -1.2,
    animationDurationSeconds: 4.7,
    zIndex: 3,
  },
  {
    id: 'banner-domus-left',
    kind: 'banner',
    assetPath: ambientAssets['banner-red'],
    x: 1028,
    y: 704,
    width: 42,
    height: 72,
    opacity: 0.96,
    animationDelaySeconds: -0.4,
    animationDurationSeconds: 1.8,
    zIndex: 8,
  },
  {
    id: 'banner-domus-right',
    kind: 'banner',
    assetPath: ambientAssets['banner-red'],
    x: 1290,
    y: 704,
    width: 42,
    height: 72,
    opacity: 0.96,
    animationDelaySeconds: -1.1,
    animationDurationSeconds: 1.9,
    zIndex: 8,
  },
  {
    id: 'banner-arena-gate',
    kind: 'banner',
    assetPath: ambientAssets['banner-red'],
    x: 2028,
    y: 626,
    width: 46,
    height: 78,
    rotation: 2,
    opacity: 0.98,
    animationDelaySeconds: -0.7,
    animationDurationSeconds: 1.7,
    zIndex: 8,
  },
  {
    id: 'banner-south-gate',
    kind: 'banner',
    assetPath: ambientAssets['banner-red'],
    x: 1172,
    y: 1162,
    width: 44,
    height: 76,
    rotation: -1,
    opacity: 0.94,
    animationDelaySeconds: -1.5,
    animationDurationSeconds: 2.1,
    zIndex: 8,
  },
  {
    id: 'smoke-canteen-hearth',
    kind: 'smoke',
    assetPath: ambientAssets['smoke-puff'],
    x: 868,
    y: 482,
    width: 54,
    height: 54,
    opacity: 0.58,
    animationDelaySeconds: -2.8,
    animationDurationSeconds: 6.8,
    zIndex: 8,
  },
  {
    id: 'smoke-market-stall',
    kind: 'smoke',
    assetPath: ambientAssets['smoke-puff'],
    x: 312,
    y: 738,
    width: 48,
    height: 48,
    opacity: 0.46,
    animationDelaySeconds: -4.2,
    animationDurationSeconds: 8,
    zIndex: 8,
  },
  {
    id: 'crowd-arena-north',
    kind: 'crowd',
    assetPath: ambientAssets['crowd-dot'],
    x: 2078,
    y: 476,
    width: 24,
    height: 24,
    opacity: 0.78,
    animationDelaySeconds: -0.2,
    animationDurationSeconds: 2.6,
    zIndex: 7,
  },
  {
    id: 'crowd-arena-west',
    kind: 'crowd',
    assetPath: ambientAssets['crowd-dot'],
    x: 2014,
    y: 520,
    width: 22,
    height: 22,
    opacity: 0.7,
    animationDelaySeconds: -1.3,
    animationDurationSeconds: 2.9,
    zIndex: 7,
  },
  {
    id: 'crowd-arena-east',
    kind: 'crowd',
    assetPath: ambientAssets['crowd-dot'],
    x: 2198,
    y: 540,
    width: 22,
    height: 22,
    opacity: 0.72,
    animationDelaySeconds: -2,
    animationDurationSeconds: 2.7,
    zIndex: 7,
  },
  {
    id: 'crowd-arena-south',
    kind: 'crowd',
    assetPath: ambientAssets['crowd-dot'],
    x: 2118,
    y: 612,
    width: 20,
    height: 20,
    opacity: 0.66,
    animationDelaySeconds: -1.7,
    animationDurationSeconds: 3.2,
    zIndex: 7,
  },
];
