import type { MapRect } from './map-layout';
import { VISUAL_ASSET_MANIFEST } from './visual-assets';

export type MapAmbientElementKind =
  | 'cloud'
  | 'grass'
  | 'banner'
  | 'torch'
  | 'smoke'
  | 'steam'
  | 'waterShimmer'
  | 'seaShimmer'
  | 'bird'
  | 'boat'
  | 'glow'
  | 'sparkle'
  | 'sway'
  | 'dummy'
  | 'crowd'
  | 'awning'
  | 'dust';

export interface MapAmbientElementDefinition extends MapRect {
  id: string;
  kind: MapAmbientElementKind;
  assetPath: string;
  rotation?: number;
  scale?: number;
  opacity?: number;
  animationDelaySeconds?: number;
  animationDurationSeconds?: number;
  zIndex?: number;
}

export interface MapWaterAnimationDefinition extends MapRect {
  id: string;
  color: string;
  lineCount: number;
  lineWidth: number;
  opacity: number;
  speed: number;
}

const ambientAssets = VISUAL_ASSET_MANIFEST.map.ambient;

export const LUDUS_MAP_WATER_ANIMATION: MapWaterAnimationDefinition = {
  id: 'coastal-sea',
  x: 0,
  y: 0,
  width: 2400,
  height: 150,
  color: '#e8fbff',
  lineCount: 14,
  lineWidth: 3,
  opacity: 0.24,
  speed: 0.18,
};

export const LUDUS_MAP_AMBIENT_ELEMENTS: MapAmbientElementDefinition[] = [
  {
    id: 'grass-market-road-01',
    kind: 'grass',
    assetPath: ambientAssets['grass-tuft-01'],
    x: 650,
    y: 738,
    width: 42,
    height: 42,
    rotation: -6,
    opacity: 0.84,
    animationDelaySeconds: -0.8,
    animationDurationSeconds: 3.8,
    zIndex: 3,
  },
  {
    id: 'grass-market-road-02',
    kind: 'grass',
    assetPath: ambientAssets['grass-tuft-01'],
    x: 785,
    y: 825,
    width: 34,
    height: 34,
    rotation: 5,
    opacity: 0.78,
    animationDelaySeconds: -1.7,
    animationDurationSeconds: 4.4,
    zIndex: 3,
  },
  {
    id: 'grass-domus-path',
    kind: 'grass',
    assetPath: ambientAssets['grass-tuft-01'],
    x: 1325,
    y: 975,
    width: 38,
    height: 38,
    rotation: 8,
    opacity: 0.8,
    animationDelaySeconds: -2.4,
    animationDurationSeconds: 4.1,
    zIndex: 3,
  },
  {
    id: 'grass-training-fence',
    kind: 'grass',
    assetPath: ambientAssets['grass-tuft-01'],
    x: 1668,
    y: 1036,
    width: 46,
    height: 46,
    rotation: -3,
    opacity: 0.82,
    animationDelaySeconds: -3.1,
    animationDurationSeconds: 5,
    zIndex: 3,
  },
  {
    id: 'grass-arena-road',
    kind: 'grass',
    assetPath: ambientAssets['grass-tuft-01'],
    x: 1848,
    y: 655,
    width: 36,
    height: 36,
    rotation: 9,
    opacity: 0.72,
    animationDelaySeconds: -1.2,
    animationDurationSeconds: 4.7,
    zIndex: 3,
  },
  {
    id: 'banner-north-overlook',
    kind: 'banner',
    assetPath: ambientAssets['banner-red'],
    x: 1040,
    y: 258,
    width: 42,
    height: 72,
    opacity: 0.96,
    animationDelaySeconds: -0.4,
    animationDurationSeconds: 1.8,
    zIndex: 8,
  },
  {
    id: 'banner-domus-right',
    kind: 'banner',
    assetPath: ambientAssets['banner-red'],
    x: 1410,
    y: 686,
    width: 42,
    height: 72,
    opacity: 0.96,
    animationDelaySeconds: -1.1,
    animationDurationSeconds: 1.9,
    zIndex: 8,
  },
  {
    id: 'banner-arena-gate',
    kind: 'banner',
    assetPath: ambientAssets['banner-red'],
    x: 2225,
    y: 608,
    width: 46,
    height: 78,
    rotation: 2,
    opacity: 0.98,
    animationDelaySeconds: -0.7,
    animationDurationSeconds: 1.7,
    zIndex: 8,
  },
  {
    id: 'banner-south-gate',
    kind: 'banner',
    assetPath: ambientAssets['banner-red'],
    x: 1120,
    y: 1360,
    width: 44,
    height: 76,
    rotation: -1,
    opacity: 0.94,
    animationDelaySeconds: -1.5,
    animationDurationSeconds: 2.1,
    zIndex: 8,
  },
  {
    id: 'smoke-canteen-hearth',
    kind: 'smoke',
    assetPath: ambientAssets['smoke-puff'],
    x: 798,
    y: 355,
    width: 54,
    height: 54,
    opacity: 0.58,
    animationDelaySeconds: -2.8,
    animationDurationSeconds: 6.8,
    zIndex: 8,
  },
  {
    id: 'smoke-market-stall',
    kind: 'smoke',
    assetPath: ambientAssets['smoke-puff'],
    x: 312,
    y: 682,
    width: 48,
    height: 48,
    opacity: 0.46,
    animationDelaySeconds: -4.2,
    animationDurationSeconds: 8,
    zIndex: 8,
  },
  {
    id: 'dust-training-west',
    kind: 'dust',
    assetPath: ambientAssets['smoke-puff'],
    x: 1765,
    y: 965,
    width: 58,
    height: 42,
    opacity: 0.22,
    animationDelaySeconds: -2.3,
    animationDurationSeconds: 5.4,
    zIndex: 7,
  },
  {
    id: 'dust-training-east',
    kind: 'dust',
    assetPath: ambientAssets['smoke-puff'],
    x: 2050,
    y: 1030,
    width: 62,
    height: 44,
    opacity: 0.2,
    animationDelaySeconds: -4,
    animationDurationSeconds: 6.1,
    zIndex: 7,
  },
  {
    id: 'awning-market-left',
    kind: 'awning',
    assetPath: ambientAssets['banner-red'],
    x: 205,
    y: 640,
    width: 78,
    height: 42,
    rotation: 88,
    opacity: 0.88,
    animationDelaySeconds: -0.5,
    animationDurationSeconds: 2.2,
    zIndex: 8,
  },
  {
    id: 'awning-market-right',
    kind: 'awning',
    assetPath: ambientAssets['banner-red'],
    x: 490,
    y: 640,
    width: 78,
    height: 42,
    rotation: 88,
    opacity: 0.82,
    animationDelaySeconds: -1.5,
    animationDurationSeconds: 2.4,
    zIndex: 8,
  },
  {
    id: 'crowd-arena-north',
    kind: 'crowd',
    assetPath: ambientAssets['crowd-dot'],
    x: 1980,
    y: 320,
    width: 24,
    height: 24,
    opacity: 0.78,
    animationDelaySeconds: -0.2,
    animationDurationSeconds: 2.6,
    zIndex: 7,
  },
  {
    id: 'crowd-arena-west',
    kind: 'crowd',
    assetPath: ambientAssets['crowd-dot'],
    x: 1840,
    y: 420,
    width: 22,
    height: 22,
    opacity: 0.7,
    animationDelaySeconds: -1.3,
    animationDurationSeconds: 2.9,
    zIndex: 7,
  },
  {
    id: 'crowd-arena-east',
    kind: 'crowd',
    assetPath: ambientAssets['crowd-dot'],
    x: 2145,
    y: 430,
    width: 22,
    height: 22,
    opacity: 0.72,
    animationDelaySeconds: -2,
    animationDurationSeconds: 2.7,
    zIndex: 7,
  },
  {
    id: 'crowd-arena-south',
    kind: 'crowd',
    assetPath: ambientAssets['crowd-dot'],
    x: 1995,
    y: 582,
    width: 20,
    height: 20,
    opacity: 0.66,
    animationDelaySeconds: -1.7,
    animationDurationSeconds: 3.2,
    zIndex: 7,
  },
  {
    id: 'boat-cliff-west',
    kind: 'boat',
    assetPath: ambientAssets['boat-small'],
    x: 545,
    y: 48,
    width: 62,
    height: 46,
    opacity: 0.72,
    animationDelaySeconds: -5.3,
    animationDurationSeconds: 8.4,
    zIndex: 1,
  },
  {
    id: 'bird-cliff-west',
    kind: 'bird',
    assetPath: ambientAssets['bird-gull-small'],
    x: 780,
    y: 188,
    width: 38,
    height: 26,
    opacity: 0.62,
    animationDelaySeconds: -7,
    animationDurationSeconds: 18,
    zIndex: 2,
  },
  {
    id: 'bird-cliff-east',
    kind: 'bird',
    assetPath: ambientAssets['bird-gull-small'],
    x: 1540,
    y: 205,
    width: 34,
    height: 24,
    rotation: -4,
    opacity: 0.5,
    animationDelaySeconds: -12,
    animationDurationSeconds: 22,
    zIndex: 2,
  },
  {
    id: 'steam-canteen-pot',
    kind: 'steam',
    assetPath: ambientAssets['steam-puff-small'],
    x: 466,
    y: 474,
    width: 28,
    height: 28,
    opacity: 0.34,
    animationDelaySeconds: -1.4,
    animationDurationSeconds: 5.5,
    zIndex: 8,
  },
  {
    id: 'sparkle-canteen-hearth',
    kind: 'sparkle',
    assetPath: ambientAssets['sparkle-small'],
    x: 588,
    y: 494,
    width: 20,
    height: 20,
    opacity: 0.42,
    animationDelaySeconds: -3.8,
    animationDurationSeconds: 6.2,
    zIndex: 8,
  },
  {
    id: 'torch-canteen-hearth',
    kind: 'torch',
    assetPath: ambientAssets['torch-on'],
    x: 458,
    y: 480,
    width: 26,
    height: 36,
    opacity: 0.46,
    animationDelaySeconds: -1.1,
    animationDurationSeconds: 1.8,
    zIndex: 8,
  },
  {
    id: 'glow-dormitory-lamp',
    kind: 'glow',
    assetPath: ambientAssets['warm-window-glow'],
    x: 784,
    y: 1135,
    width: 32,
    height: 34,
    opacity: 0.42,
    animationDelaySeconds: -1.5,
    animationDurationSeconds: 3.6,
    zIndex: 8,
  },
  {
    id: 'sway-dormitory-curtain',
    kind: 'sway',
    assetPath: ambientAssets['rope-strip-small'],
    x: 402,
    y: 1126,
    width: 26,
    height: 42,
    rotation: -6,
    opacity: 0.42,
    animationDelaySeconds: -2.6,
    animationDurationSeconds: 4.8,
    zIndex: 8,
  },
  {
    id: 'blanket-dormitory-breathe',
    kind: 'glow',
    assetPath: ambientAssets['warm-window-glow'],
    x: 584,
    y: 1248,
    width: 34,
    height: 16,
    opacity: 0.12,
    animationDelaySeconds: -4.2,
    animationDurationSeconds: 7.8,
    zIndex: 8,
  },
  {
    id: 'herbs-infirmary-sway',
    kind: 'sway',
    assetPath: ambientAssets['rope-strip-small'],
    x: 1358,
    y: 1112,
    width: 24,
    height: 42,
    rotation: 4,
    opacity: 0.38,
    animationDelaySeconds: -3.9,
    animationDurationSeconds: 5.2,
    zIndex: 8,
  },
  {
    id: 'basin-infirmary-shimmer',
    kind: 'waterShimmer',
    assetPath: ambientAssets['water-shimmer-small'],
    x: 1406,
    y: 1128,
    width: 56,
    height: 18,
    opacity: 0.34,
    animationDelaySeconds: -1.8,
    animationDurationSeconds: 4.4,
    zIndex: 8,
  },
  {
    id: 'incense-infirmary',
    kind: 'steam',
    assetPath: ambientAssets['incense-wisp-small'],
    x: 1125,
    y: 1270,
    width: 28,
    height: 44,
    opacity: 0.28,
    animationDelaySeconds: -5.1,
    animationDurationSeconds: 7.2,
    zIndex: 8,
  },
  {
    id: 'glow-infirmary-lamp',
    kind: 'glow',
    assetPath: ambientAssets['warm-window-glow'],
    x: 1456,
    y: 1260,
    width: 34,
    height: 36,
    opacity: 0.38,
    animationDelaySeconds: -2.2,
    animationDurationSeconds: 3.4,
    zIndex: 8,
  },
  {
    id: 'dummy-training-wobble',
    kind: 'dummy',
    assetPath: ambientAssets['rope-strip-small'],
    x: 1752,
    y: 860,
    width: 22,
    height: 44,
    rotation: 1,
    opacity: 0.36,
    animationDelaySeconds: -2.4,
    animationDurationSeconds: 3.8,
    zIndex: 8,
  },
  {
    id: 'rope-training-sway',
    kind: 'sway',
    assetPath: ambientAssets['rope-strip-small'],
    x: 2110,
    y: 1005,
    width: 34,
    height: 46,
    rotation: 85,
    opacity: 0.34,
    animationDelaySeconds: -1.2,
    animationDurationSeconds: 5.6,
    zIndex: 8,
  },
  {
    id: 'banner-training-sway',
    kind: 'banner',
    assetPath: ambientAssets['banner-red'],
    x: 1685,
    y: 802,
    width: 34,
    height: 58,
    opacity: 0.78,
    animationDelaySeconds: -3.3,
    animationDurationSeconds: 3.1,
    zIndex: 8,
  },
  {
    id: 'fountain-pleasure-shimmer',
    kind: 'waterShimmer',
    assetPath: ambientAssets['water-shimmer-small'],
    x: 1120,
    y: 390,
    width: 58,
    height: 20,
    opacity: 0.38,
    animationDelaySeconds: -0.7,
    animationDurationSeconds: 4.2,
    zIndex: 8,
  },
  {
    id: 'curtain-pleasure-sway',
    kind: 'sway',
    assetPath: ambientAssets['rope-strip-small'],
    x: 1486,
    y: 357,
    width: 24,
    height: 48,
    rotation: -4,
    opacity: 0.42,
    animationDelaySeconds: -2.9,
    animationDurationSeconds: 5.1,
    zIndex: 8,
  },
  {
    id: 'glow-pleasure-lamp',
    kind: 'glow',
    assetPath: ambientAssets['warm-window-glow'],
    x: 1435,
    y: 534,
    width: 36,
    height: 36,
    opacity: 0.34,
    animationDelaySeconds: -2.2,
    animationDurationSeconds: 3.2,
    zIndex: 8,
  },
  {
    id: 'sparkle-pleasure-garden',
    kind: 'sparkle',
    assetPath: ambientAssets['sparkle-small'],
    x: 1298,
    y: 512,
    width: 18,
    height: 18,
    opacity: 0.24,
    animationDelaySeconds: -6.2,
    animationDurationSeconds: 8.5,
    zIndex: 8,
  },
  {
    id: 'torch-domus-brazier-left',
    kind: 'torch',
    assetPath: ambientAssets['torch-on'],
    x: 980,
    y: 902,
    width: 28,
    height: 38,
    opacity: 0.46,
    animationDelaySeconds: -0.8,
    animationDurationSeconds: 1.7,
    zIndex: 8,
  },
  {
    id: 'torch-domus-brazier-right',
    kind: 'torch',
    assetPath: ambientAssets['torch-on'],
    x: 1365,
    y: 900,
    width: 28,
    height: 38,
    opacity: 0.42,
    animationDelaySeconds: -1.8,
    animationDurationSeconds: 1.9,
    zIndex: 8,
  },
  {
    id: 'glow-domus-window-left',
    kind: 'glow',
    assetPath: ambientAssets['warm-window-glow'],
    x: 956,
    y: 672,
    width: 38,
    height: 40,
    opacity: 0.46,
    animationDelaySeconds: -3.4,
    animationDurationSeconds: 4.2,
    zIndex: 8,
  },
  {
    id: 'glow-domus-window-right',
    kind: 'glow',
    assetPath: ambientAssets['warm-window-glow'],
    x: 1372,
    y: 680,
    width: 38,
    height: 40,
    opacity: 0.42,
    animationDelaySeconds: -4.1,
    animationDurationSeconds: 4.6,
    zIndex: 8,
  },
  {
    id: 'market-crowd-dot-01',
    kind: 'crowd',
    assetPath: ambientAssets['crowd-dot'],
    x: 255,
    y: 708,
    width: 16,
    height: 16,
    opacity: 0.5,
    animationDelaySeconds: -0.6,
    animationDurationSeconds: 3.2,
    zIndex: 8,
  },
  {
    id: 'market-crowd-dot-02',
    kind: 'crowd',
    assetPath: ambientAssets['crowd-dot'],
    x: 494,
    y: 795,
    width: 14,
    height: 14,
    opacity: 0.45,
    animationDelaySeconds: -2.4,
    animationDurationSeconds: 3.5,
    zIndex: 8,
  },
  {
    id: 'dust-market-road',
    kind: 'dust',
    assetPath: ambientAssets['smoke-puff'],
    x: 595,
    y: 812,
    width: 42,
    height: 30,
    opacity: 0.16,
    animationDelaySeconds: -5.5,
    animationDurationSeconds: 8.2,
    zIndex: 7,
  },
  {
    id: 'arena-sand-shimmer',
    kind: 'waterShimmer',
    assetPath: ambientAssets['water-shimmer-small'],
    x: 1948,
    y: 382,
    width: 78,
    height: 20,
    opacity: 0.18,
    animationDelaySeconds: -3.8,
    animationDurationSeconds: 5.8,
    zIndex: 7,
  },
  {
    id: 'torch-arena-left',
    kind: 'torch',
    assetPath: ambientAssets['torch-on'],
    x: 1828,
    y: 580,
    width: 28,
    height: 40,
    opacity: 0.42,
    animationDelaySeconds: -0.4,
    animationDurationSeconds: 1.8,
    zIndex: 8,
  },
  {
    id: 'torch-arena-right',
    kind: 'torch',
    assetPath: ambientAssets['torch-on'],
    x: 2145,
    y: 582,
    width: 28,
    height: 40,
    opacity: 0.42,
    animationDelaySeconds: -1.4,
    animationDurationSeconds: 1.8,
    zIndex: 8,
  },
];
