import type {
  BuildingImprovementDefinition,
  BuildingPolicyDefinition,
} from '../../domain/buildings/types';

export const BUILDING_IMPROVEMENTS: BuildingImprovementDefinition[] = [
  {
    id: 'dormitoryExtraBunk1',
    buildingId: 'dormitory',
    nameKey: 'improvements.dormitoryExtraBunk1.name',
    descriptionKey: 'improvements.dormitoryExtraBunk1.description',
    cost: 120,
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseCapacity', value: 1, target: 'ludus' }],
  },
  {
    id: 'dormitoryExtraBunk2',
    buildingId: 'dormitory',
    nameKey: 'improvements.dormitoryExtraBunk2.name',
    descriptionKey: 'improvements.dormitoryExtraBunk2.description',
    cost: 220,
    requiredBuildingLevel: 2,
    requiredImprovementIds: ['dormitoryExtraBunk1'],
    effects: [{ type: 'increaseCapacity', value: 1, target: 'ludus' }],
  },
  {
    id: 'dormitoryExtraBunk3',
    buildingId: 'dormitory',
    nameKey: 'improvements.dormitoryExtraBunk3.name',
    descriptionKey: 'improvements.dormitoryExtraBunk3.description',
    cost: 420,
    requiredBuildingLevel: 3,
    requiredImprovementIds: ['dormitoryExtraBunk2'],
    effects: [{ type: 'increaseCapacity', value: 1, target: 'ludus' }],
  },
  {
    id: 'dormitoryExtraBunk4',
    buildingId: 'dormitory',
    nameKey: 'improvements.dormitoryExtraBunk4.name',
    descriptionKey: 'improvements.dormitoryExtraBunk4.description',
    cost: 800,
    requiredBuildingLevel: 4,
    requiredImprovementIds: ['dormitoryExtraBunk3'],
    effects: [{ type: 'increaseCapacity', value: 1, target: 'ludus' }],
  },
  {
    id: 'dormitoryExtraBunk5',
    buildingId: 'dormitory',
    nameKey: 'improvements.dormitoryExtraBunk5.name',
    descriptionKey: 'improvements.dormitoryExtraBunk5.description',
    cost: 1500,
    requiredBuildingLevel: 5,
    requiredImprovementIds: ['dormitoryExtraBunk4'],
    effects: [{ type: 'increaseCapacity', value: 1, target: 'ludus' }],
  },
  {
    id: 'strawBeds',
    buildingId: 'dormitory',
    nameKey: 'improvements.strawBeds.name',
    descriptionKey: 'improvements.strawBeds.description',
    cost: 70,
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseHappiness', value: 5, target: 'ludus' }],
  },
  {
    id: 'woodenBeds',
    buildingId: 'dormitory',
    nameKey: 'improvements.woodenBeds.name',
    descriptionKey: 'improvements.woodenBeds.description',
    cost: 130,
    requiredBuildingLevel: 1,
    requiredImprovementIds: ['strawBeds'],
    effects: [{ type: 'increaseHappiness', value: 8, target: 'ludus' }],
  },
  {
    id: 'quietQuarters',
    buildingId: 'dormitory',
    nameKey: 'improvements.quietQuarters.name',
    descriptionKey: 'improvements.quietQuarters.description',
    cost: 150,
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseHappiness', value: 5, target: 'ludus' }],
  },
  {
    id: 'sparringRing',
    buildingId: 'trainingGround',
    nameKey: 'improvements.sparringRing.name',
    descriptionKey: 'improvements.sparringRing.description',
    cost: 160,
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseTrainingExperience', value: 1, target: 'plannedGladiators' }],
  },
  {
    id: 'advancedDoctoreTools',
    buildingId: 'trainingGround',
    nameKey: 'improvements.advancedDoctoreTools.name',
    descriptionKey: 'improvements.advancedDoctoreTools.description',
    cost: 220,
    requiredBuildingLevel: 2,
    effects: [{ type: 'reduceInjuryRisk', value: 3, target: 'plannedGladiators' }],
  },
];

export const BUILDING_POLICIES: BuildingPolicyDefinition[] = [
  {
    id: 'balancedTraining',
    buildingId: 'trainingGround',
    nameKey: 'policies.balancedTraining.name',
    descriptionKey: 'policies.balancedTraining.description',
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseTrainingExperience', value: 1, target: 'plannedGladiators' }],
  },
  {
    id: 'strengthDoctrine',
    buildingId: 'trainingGround',
    nameKey: 'policies.strengthDoctrine.name',
    descriptionKey: 'policies.strengthDoctrine.description',
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseTrainingExperience', value: 1, target: 'plannedGladiators' }],
  },
  {
    id: 'agilityDoctrine',
    buildingId: 'trainingGround',
    nameKey: 'policies.agilityDoctrine.name',
    descriptionKey: 'policies.agilityDoctrine.description',
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseTrainingExperience', value: 1, target: 'plannedGladiators' }],
  },
  {
    id: 'defensiveDoctrine',
    buildingId: 'trainingGround',
    nameKey: 'policies.defensiveDoctrine.name',
    descriptionKey: 'policies.defensiveDoctrine.description',
    requiredBuildingLevel: 1,
    effects: [{ type: 'increaseTrainingExperience', value: 1, target: 'plannedGladiators' }],
  },
  {
    id: 'brutalDiscipline',
    buildingId: 'trainingGround',
    nameKey: 'policies.brutalDiscipline.name',
    descriptionKey: 'policies.brutalDiscipline.description',
    requiredBuildingLevel: 2,
    effects: [
      { type: 'increaseTrainingExperience', value: 2, target: 'plannedGladiators' },
      { type: 'reduceInjuryRisk', value: -2, target: 'allGladiators' },
    ],
  },
];
