import {
  RiAncientGateFill,
  RiAddCircleFill,
  RiArrowLeftFill,
  RiArrowRightFill,
  RiBarChartBoxFill,
  RiCalendarCheckFill,
  RiCalendarFill,
  RiCheckFill,
  RiCloseFill,
  RiCloudOffFill,
  RiCoinsFill,
  RiDiceFill,
  RiEmotionHappyFill,
  RiErrorWarningFill,
  RiEyeFill,
  RiFlashlightFill,
  RiFolderOpenFill,
  RiFootprintFill,
  RiGroupFill,
  RiHammerFill,
  RiHeartFill,
  RiLogoutBoxRFill,
  RiMapPinFill,
  RiMedalFill,
  RiPauseFill,
  RiPlayFill,
  RiSaveFill,
  RiSettings3Fill,
  RiShoppingCartFill,
  RiSkull2Fill,
  RiSkipBackFill,
  RiSkipForwardFill,
  RiSparklingFill,
  RiStarFill,
  RiTargetFill,
  RiTrophyFill,
  RiUserMinusFill,
  RiWeightFill,
  RiSettings5Fill,
  RiWindyFill,
  type RemixiconComponentType,
  RiSwordFill,
  RiShieldFill,
} from '@remixicon/react';

interface GameIconDefinition {
  Icon: RemixiconComponentType;
  color: string;
}

export const GAME_ICON_DEFINITIONS = {
  agility: { Icon: RiWindyFill, color: '#5f8fb7' },
  age: { Icon: RiCalendarFill, color: '#c19b57' },
  alert: { Icon: RiErrorWarningFill, color: '#d39942' },
  arrowRight: { Icon: RiArrowRightFill, color: '#f7e6b3' },
  assignment: { Icon: RiMapPinFill, color: '#d6a34a' },
  back: { Icon: RiArrowLeftFill, color: '#f7e6b3' },
  capacity: { Icon: RiGroupFill, color: '#c19b57' },
  check: { Icon: RiCheckFill, color: '#78c46b' },
  close: { Icon: RiCloseFill, color: '#f7e6b3' },
  cloudOff: { Icon: RiCloudOffFill, color: '#9a8d74' },
  combatFeint: { Icon: RiFootprintFill, color: '#5f8fb7' },
  combatPressure: { Icon: RiTargetFill, color: '#b55339' },
  combatStrike: { Icon: RiSwordFill, color: '#b55339' },
  defense: { Icon: RiShieldFill, color: '#8f8a80' },
  defeat: { Icon: RiSkull2Fill, color: '#b55339' },
  dice: { Icon: RiDiceFill, color: '#d6a34a' },
  energy: { Icon: RiFlashlightFill, color: '#d39942' },
  experience: { Icon: RiBarChartBoxFill, color: '#78c46b' },
  folderOpen: { Icon: RiFolderOpenFill, color: '#d6a34a' },
  hammer: { Icon: RiHammerFill, color: '#d6a34a' },
  health: { Icon: RiHeartFill, color: '#b33a2e' },
  happiness: { Icon: RiEmotionHappyFill, color: '#ffd76a' },
  landmark: { Icon: RiAncientGateFill, color: '#d6a34a' },
  level: { Icon: RiStarFill, color: '#ffd76a' },
  logout: { Icon: RiLogoutBoxRFill, color: '#b55339' },
  menu: { Icon: RiSettings5Fill, color: '#f7e6b3' },
  morale: { Icon: RiEmotionHappyFill, color: '#ffd76a' },
  nextDay: { Icon: RiSkipForwardFill, color: '#f7e6b3' },
  pause: { Icon: RiPauseFill, color: '#f7e6b3' },
  play: { Icon: RiPlayFill, color: '#f7e6b3' },
  reputation: { Icon: RiMedalFill, color: '#78c46b' },
  record: { Icon: RiSwordFill, color: '#b55339' },
  save: { Icon: RiSaveFill, color: '#78c46b' },
  settings: { Icon: RiSettings3Fill, color: '#d6a34a' },
  shoppingCart: { Icon: RiShoppingCartFill, color: '#d6a34a' },
  skipBack: { Icon: RiSkipBackFill, color: '#f7e6b3' },
  skillPoint: { Icon: RiAddCircleFill, color: '#78c46b' },
  strength: { Icon: RiWeightFill, color: '#b56f3c' },
  treasury: { Icon: RiCoinsFill, color: '#ffd76a' },
  training: { Icon: RiFootprintFill, color: '#5f8fb7' },
  userMinus: { Icon: RiUserMinusFill, color: '#b55339' },
  victory: { Icon: RiTrophyFill, color: '#d6a34a' },
  view: { Icon: RiEyeFill, color: '#d6a34a' },
  warning: { Icon: RiSparklingFill, color: '#d39942' },
  weeklyPlanning: { Icon: RiCalendarCheckFill, color: '#d6a34a' },
  xp: { Icon: RiBarChartBoxFill, color: '#78c46b' },
} satisfies Record<string, GameIconDefinition>;

export type GameIconName = keyof typeof GAME_ICON_DEFINITIONS;
